from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

AUTO_SEARCH_REWARD_TITLE = Button(area=(334, 149, 369, 165), color=(182, 193, 204), button=(334, 149, 369, 165), file='./assets/en/azur_stats/AUTO_SEARCH_REWARD_TITLE.png')
BATTLE_STATUS_ENEMY_NAME = Button(area=(781, 283, 965, 322), color=(92, 102, 119), button=(781, 283, 965, 322), file='./assets/en/azur_stats/BATTLE_STATUS_ENEMY_NAME.png')
COMMISSION_DONE = Button(area=(352, 103, 444, 144), color=(191, 182, 149), button=(352, 103, 444, 144), file='./assets/en/azur_stats/COMMISSION_DONE.png')
COMMISSION_NAME = Button(area=(293, 162, 593, 183), color=(101, 117, 147), button=(293, 162, 593, 183), file='./assets/en/azur_stats/COMMISSION_NAME.png')
COMMISSION_PERFECT = Button(area=(251, 97, 430, 144), color=(171, 170, 151), button=(251, 97, 430, 144), file='./assets/en/azur_stats/COMMISSION_PERFECT.png')
FOCUS_SERIES = Button(area=(821, 652, 859, 690), color=(87, 90, 109), button=(821, 652, 859, 690), file='./assets/en/azur_stats/FOCUS_SERIES.png')
HAS_RESEARCH_QUEUE = Button(area=(44, 216, 64, 236), color=(50, 54, 82), button=(44, 216, 64, 236), file='./assets/en/azur_stats/HAS_RESEARCH_QUEUE.png')
MEOWFFICER_NAME = Button(area=(977, 203, 1127, 228), color=(236, 231, 220), button=(977, 203, 1127, 228), file='./assets/en/azur_stats/MEOWFFICER_NAME.png')
MEOWFFICER_TALENT_DETAIL = Button(area=(485, 430, 770, 451), color=(230, 225, 228), button=(485, 430, 770, 451), file='./assets/en/azur_stats/MEOWFFICER_TALENT_DETAIL.png')
QUEUE_OCR_RESEARCH_1 = Button(area=(56, 280, 270, 346), color=(122, 154, 200), button=(56, 280, 270, 346), file='./assets/en/azur_stats/QUEUE_OCR_RESEARCH_1.png')
QUEUE_OCR_RESEARCH_2 = Button(area=(283, 281, 497, 347), color=(202, 178, 142), button=(283, 281, 497, 347), file='./assets/en/azur_stats/QUEUE_OCR_RESEARCH_2.png')
QUEUE_OCR_RESEARCH_3 = Button(area=(513, 280, 727, 346), color=(122, 155, 203), button=(513, 280, 727, 346), file='./assets/en/azur_stats/QUEUE_OCR_RESEARCH_3.png')
QUEUE_OCR_RESEARCH_4 = Button(area=(739, 281, 953, 347), color=(202, 178, 143), button=(739, 281, 953, 347), file='./assets/en/azur_stats/QUEUE_OCR_RESEARCH_4.png')
QUEUE_OCR_RESEARCH_5 = Button(area=(969, 280, 1183, 346), color=(124, 156, 205), button=(969, 280, 1183, 346), file='./assets/en/azur_stats/QUEUE_OCR_RESEARCH_5.png')
QUEUE_SETIES_1 = Button(area=(66, 127, 99, 151), color=(196, 107, 90), button=(66, 127, 99, 151), file='./assets/en/azur_stats/QUEUE_SETIES_1.png')
QUEUE_SETIES_2 = Button(area=(294, 127, 327, 151), color=(80, 98, 204), button=(294, 127, 327, 151), file='./assets/en/azur_stats/QUEUE_SETIES_2.png')
QUEUE_SETIES_3 = Button(area=(523, 127, 556, 151), color=(200, 113, 98), button=(523, 127, 556, 151), file='./assets/en/azur_stats/QUEUE_SETIES_3.png')
QUEUE_SETIES_4 = Button(area=(751, 127, 784, 151), color=(80, 101, 211), button=(751, 127, 784, 151), file='./assets/en/azur_stats/QUEUE_SETIES_4.png')
QUEUE_SETIES_5 = Button(area=(979, 127, 1012, 151), color=(200, 114, 100), button=(979, 127, 1012, 151), file='./assets/en/azur_stats/QUEUE_SETIES_5.png')
TEMPLATE_MEOWFFICER_NAME_CHECK = Template(file='./assets/en/azur_stats/TEMPLATE_MEOWFFICER_NAME_CHECK.png')
TEMPLATE_RESEARCH_FINISHED = Template(file='./assets/en/azur_stats/TEMPLATE_RESEARCH_FINISHED.png')
