from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ADD_NEW_STUDENT = Button(area=(417, 375, 438, 398), color=(81, 91, 106), button=(417, 375, 438, 398), file='./assets/en/tactical/ADD_NEW_STUDENT.png')
BOOK_EMPTY_POPUP = Button(area=(880, 180, 908, 209), color=(211, 109, 105), button=(880, 180, 908, 209), file='./assets/en/tactical/BOOK_EMPTY_POPUP.png')
OCR_SKILL_EXP = Button(area=(771, 191, 951, 209), color=(72, 82, 83), button=(771, 191, 951, 209), file='./assets/en/tactical/OCR_SKILL_EXP.png')
RAPID_TRAINING = Button(area=(518, 568, 585, 580), color=(229, 205, 156), button=(518, 568, 585, 580), file='./assets/en/tactical/RAPID_TRAINING.png')
REWARD_2 = Button(area=(403, 416, 504, 432), color=(240, 201, 145), button=(392, 404, 515, 445), file='./assets/en/tactical/REWARD_2.png')
SKILL_CONFIRM = Button(area=(600, 558, 681, 581), color=(167, 191, 223), button=(600, 558, 681, 581), file='./assets/en/tactical/SKILL_CONFIRM.png')
TACTICAL_CLASS_CANCEL = Button(area=(836, 591, 973, 639), color=(163, 164, 164), button=(836, 591, 973, 639), file='./assets/en/tactical/TACTICAL_CLASS_CANCEL.png')
TACTICAL_CLASS_START = Button(area=(1045, 592, 1176, 640), color=(95, 137, 190), button=(1045, 592, 1176, 640), file='./assets/en/tactical/TACTICAL_CLASS_START.png')
TACTICAL_META = Button(area=(584, 559, 697, 586), color=(198, 199, 201), button=(584, 559, 697, 586), file='./assets/en/tactical/TACTICAL_META.png')
