from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BOX_AMOUNT_CONFIRM = Button(area=(773, 618, 905, 642), color=(153, 180, 213), button=(773, 618, 905, 642), file='./assets/en/storage/BOX_AMOUNT_CONFIRM.png')
BOX_AMOUNT_OCR = Button(area=(591, 298, 688, 326), color=(56, 56, 65), button=(591, 298, 688, 326), file='./assets/en/storage/BOX_AMOUNT_OCR.png')
BOX_REMAIN_AMOUNT_OCR = Button(area=(443, 407, 501, 430), color=(164, 168, 63), button=(443, 407, 501, 430), file='./assets/en/storage/BOX_REMAIN_AMOUNT_OCR.png')
BOX_USE = Button(area=(757, 498, 815, 524), color=(160, 188, 222), button=(757, 498, 815, 524), file='./assets/en/storage/BOX_USE.png')
DISASSEMBLE = Button(area=(346, 668, 467, 684), color=(193, 193, 194), button=(346, 659, 467, 698), file='./assets/en/storage/DISASSEMBLE.png')
DISASSEMBLE_CANCEL = Button(area=(881, 659, 993, 684), color=(192, 192, 193), button=(854, 649, 1021, 699), file='./assets/en/storage/DISASSEMBLE_CANCEL.png')
DISASSEMBLE_CONFIRM = Button(area=(1063, 658, 1230, 681), color=(204, 152, 145), button=(1063, 651, 1230, 697), file='./assets/en/storage/DISASSEMBLE_CONFIRM.png')
DISASSEMBLE_COUNT_OCR = Button(area=(625, 664, 685, 694), color=(72, 74, 85), button=(625, 664, 685, 694), file='./assets/en/storage/DISASSEMBLE_COUNT_OCR.png')
DISASSEMBLE_POPUP_CONFIRM = Button(area=(717, 568, 841, 590), color=(160, 187, 223), button=(708, 558, 851, 601), file='./assets/en/storage/DISASSEMBLE_POPUP_CONFIRM.png')
EQUIPMENT_EMPTY = Button(area=(1127, 353, 1155, 395), color=(95, 74, 86), button=(1127, 353, 1155, 395), file='./assets/en/storage/EQUIPMENT_EMPTY.png')
EQUIPMENT_ENTER = Button(area=(1020, 669, 1071, 686), color=(200, 161, 99), button=(954, 659, 1084, 689), file='./assets/en/storage/EQUIPMENT_ENTER.png')
EQUIPMENT_FILTER = Button(area=(746, 23, 781, 36), color=(142, 160, 201), button=(742, 13, 819, 36), file='./assets/en/storage/EQUIPMENT_FILTER.png')
EQUIPMENT_FILTER_CONFIRM = Button(area=(734, 620, 865, 643), color=(156, 183, 217), button=(727, 608, 872, 653), file='./assets/en/storage/EQUIPMENT_FILTER_CONFIRM.png')
EQUIPMENT_FULL = Button(area=(460, 499, 521, 520), color=(168, 194, 226), button=(421, 489, 566, 534), file='./assets/en/storage/EQUIPMENT_FULL.png')
MATERIAL_CHECK = Button(area=(1123, 658, 1156, 691), color=(195, 161, 99), button=(1123, 658, 1156, 691), file='./assets/en/storage/MATERIAL_CHECK.png')
MATERIAL_ENTER = Button(area=(1184, 669, 1227, 685), color=(202, 163, 103), button=(1121, 663, 1243, 685), file='./assets/en/storage/MATERIAL_ENTER.png')
MATERIAL_STABLE_CHECK = Button(area=(858, 422, 1231, 631), color=(116, 127, 145), button=(858, 422, 1231, 631), file='./assets/en/storage/MATERIAL_STABLE_CHECK.png')
METERIAL_SCROLL = Button(area=(1257, 94, 1263, 585), color=(101, 93, 56), button=(1257, 94, 1263, 585), file='./assets/en/storage/METERIAL_SCROLL.png')
TEMPLATE_BOX_T1 = Template(file='./assets/en/storage/TEMPLATE_BOX_T1.png')
TEMPLATE_BOX_T2 = Template(file='./assets/en/storage/TEMPLATE_BOX_T2.png')
TEMPLATE_BOX_T3 = Template(file='./assets/en/storage/TEMPLATE_BOX_T3.png')
TEMPLATE_BOX_T4 = Template(file='./assets/en/storage/TEMPLATE_BOX_T4.png')
