from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BATTLE_MIDDLE = Button(area=(499, 346, 530, 375), color=(160, 160, 166), button=(499, 346, 530, 375), file='./assets/en/eventstory/BATTLE_MIDDLE.png')
POPUP_RPG_STATUS = Button(area=(1001, 141, 1022, 162), color=(188, 182, 168), button=(1001, 141, 1022, 162), file='./assets/en/eventstory/POPUP_RPG_STATUS.png')
REWARD_GOT = Button(area=(1177, 672, 1233, 683), color=(201, 167, 61), button=(1177, 672, 1233, 683), file='./assets/en/eventstory/REWARD_GOT.png')
STORY_FINISHED = Button(area=(913, 347, 940, 373), color=(204, 180, 83), button=(913, 347, 940, 373), file='./assets/en/eventstory/STORY_FINISHED.png')
STORY_FIRST = Button(area=(89, 346, 116, 373), color=(199, 199, 203), button=(89, 346, 116, 373), file='./assets/en/eventstory/STORY_FIRST.png')
STORY_LAST = Button(area=(913, 347, 940, 374), color=(204, 204, 207), button=(913, 347, 940, 374), file='./assets/en/eventstory/STORY_LAST.png')
STORY_MIDDLE = Button(area=(501, 346, 528, 373), color=(199, 199, 203), button=(501, 346, 528, 373), file='./assets/en/eventstory/STORY_MIDDLE.png')
TEMPLATE_ALCHEMIST_BATTLE = Template(file='./assets/en/eventstory/TEMPLATE_ALCHEMIST_BATTLE.png')
TEMPLATE_ALCHEMIST_STORY = Template(file='./assets/en/eventstory/TEMPLATE_ALCHEMIST_STORY.png')
