from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BATTLE_PASS_RED_DOT = Button(area=(623, 105, 629, 113), color=(202, 86, 66), button=(623, 105, 629, 113), file='./assets/en/freebies/BATTLE_PASS_RED_DOT.png')
BUY_CONFIRM = Button(area=(710, 583, 860, 633), color=(92, 142, 203), button=(710, 583, 860, 633), file='./assets/en/freebies/BUY_CONFIRM.png')
DATA_KEY_COLLECT = Button(area=(256, 42, 337, 68), color=(145, 109, 72), button=(256, 42, 337, 68), file='./assets/en/freebies/DATA_KEY_COLLECT.png')
DATA_KEY_COLLECTED = Button(area=(255, 42, 338, 68), color=(113, 113, 115), button=(255, 42, 338, 68), file='./assets/en/freebies/DATA_KEY_COLLECTED.png')
FREE_SUPPLY_PACK = Button(area=(295, 617, 345, 637), color=(134, 146, 153), button=(293, 321, 373, 381), file='./assets/en/freebies/FREE_SUPPLY_PACK.png')
MAIL_BATCH_CLAIM = Button(area=(643, 525, 704, 543), color=(147, 220, 255), button=(643, 525, 704, 543), file='./assets/en/freebies/MAIL_BATCH_CLAIM.png')
MAIL_BATCH_DELETE = Button(area=(817, 526, 887, 544), color=(150, 221, 255), button=(817, 526, 887, 544), file='./assets/en/freebies/MAIL_BATCH_DELETE.png')
MAIL_ENTER = Button(area=(1207, 393, 1253, 429), color=(109, 107, 95), button=(1207, 393, 1253, 429), file='./assets/en/freebies/MAIL_ENTER.png')
MAIL_MANAGE = Button(area=(393, 641, 463, 660), color=(131, 214, 255), button=(393, 641, 463, 660), file='./assets/en/freebies/MAIL_MANAGE.png')
MAIL_SELECT_ALL = Button(area=(390, 319, 410, 339), color=(87, 88, 88), button=(390, 319, 410, 339), file='./assets/en/freebies/MAIL_SELECT_ALL.png')
MAIL_SELECT_COINS = Button(area=(562, 401, 582, 421), color=(241, 240, 241), button=(562, 401, 582, 421), file='./assets/en/freebies/MAIL_SELECT_COINS.png')
MAIL_SELECT_CUBE = Button(area=(442, 401, 462, 421), color=(241, 241, 241), button=(442, 401, 462, 421), file='./assets/en/freebies/MAIL_SELECT_CUBE.png')
MAIL_SELECT_GEMS = Button(area=(442, 441, 462, 461), color=(241, 241, 241), button=(442, 441, 462, 461), file='./assets/en/freebies/MAIL_SELECT_GEMS.png')
MAIL_SELECT_MERIT = Button(area=(802, 401, 822, 421), color=(87, 87, 88), button=(802, 401, 822, 421), file='./assets/en/freebies/MAIL_SELECT_MERIT.png')
MAIL_SELECT_OIL = Button(area=(682, 401, 702, 421), color=(241, 240, 241), button=(682, 401, 702, 421), file='./assets/en/freebies/MAIL_SELECT_OIL.png')
MAIL_WHITE_EMPTY = Button(area=(236, 365, 371, 404), color=(148, 160, 177), button=(236, 365, 371, 404), file='./assets/en/freebies/MAIL_WHITE_EMPTY.png')
OCR_DATA_KEY = Button(area=(133, 39, 250, 72), color=(82, 80, 91), button=(133, 39, 250, 72), file='./assets/en/freebies/OCR_DATA_KEY.png')
PURCHASE_POPUP = Button(area=(907, 204, 934, 229), color=(176, 130, 110), button=(907, 204, 934, 229), file='./assets/en/freebies/PURCHASE_POPUP.png')
REWARD_RECEIVE = Button(area=(1192, 522, 1254, 534), color=(195, 182, 168), button=(1192, 522, 1254, 534), file='./assets/en/freebies/REWARD_RECEIVE.png')
REWARD_RECEIVE_SP = Button(area=(1090, 580, 1197, 596), color=(168, 129, 111), button=(1090, 580, 1197, 596), file='./assets/en/freebies/REWARD_RECEIVE_SP.png')
REWARD_RECEIVE_WHITE = Button(area=(1115, 604, 1202, 620), color=(255, 209, 153), button=(1115, 604, 1202, 620), file='./assets/en/freebies/REWARD_RECEIVE_WHITE.png')
