from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

CARGO_PREPARATION_EMPTY_REPLACE = Button(area=(704, 212, 864, 232), color=(188, 188, 185), button=(704, 212, 864, 232), file='./assets/en/island_cargo_preparation/CARGO_PREPARATION_EMPTY_REPLACE.png')
CARGO_PREPARATION_REPLACE_CONFIRM = Button(area=(723, 600, 773, 626), color=(113, 209, 255), button=(723, 600, 773, 626), file='./assets/en/island_cargo_preparation/CARGO_PREPARATION_REPLACE_CONFIRM.png')
EMPTY_LIST_CHECK = Button(area=(531, 315, 776, 340), color=(204, 204, 205), button=(531, 315, 776, 340), file='./assets/en/island_cargo_preparation/EMPTY_LIST_CHECK.png')
REFRESH_BUTTON_BLUE = Button(area=(830, 85, 880, 110), color=(74, 196, 255), button=(830, 85, 880, 110), file='./assets/en/island_cargo_preparation/REFRESH_BUTTON_BLUE.png')
REFRESH_BUTTON_GREY = Button(area=(830, 85, 880, 110), color=(174, 174, 174), button=(830, 85, 880, 110), file='./assets/en/island_cargo_preparation/REFRESH_BUTTON_GREY.png')
REPLACE_PAGE_CHECK = Button(area=(407, 76, 532, 107), color=(134, 134, 135), button=(407, 76, 532, 107), file='./assets/en/island_cargo_preparation/REPLACE_PAGE_CHECK.png')
TEMPLATE_CARGO_MILK = Template(file='./assets/en/island_cargo_preparation/TEMPLATE_CARGO_MILK.png')
