from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ISLAND_PEARL_FRIEND_RANK_TAB = Button(area=(586, 91, 657, 112), color=(186, 186, 186), button=(586, 91, 657, 112), file='./assets/en/island_pearl_sell/ISLAND_PEARL_FRIEND_RANK_TAB.png')
ISLAND_PEARL_SHOP_BUY_CHECK = Button(area=(113, 22, 229, 44), color=(95, 101, 113), button=(113, 22, 229, 44), file='./assets/en/island_pearl_sell/ISLAND_PEARL_SHOP_BUY_CHECK.png')
ISLAND_PEARL_SHOP_BUY_ENTER = Button(area=(804, 447, 980, 474), color=(220, 218, 215), button=(804, 447, 980, 474), file='./assets/en/island_pearl_sell/ISLAND_PEARL_SHOP_BUY_ENTER.png')
ISLAND_PEARL_SHOP_FRIEND_ENTER = Button(area=(804, 377, 980, 411), color=(221, 223, 222), button=(804, 377, 980, 411), file='./assets/en/island_pearl_sell/ISLAND_PEARL_SHOP_FRIEND_ENTER.png')
ISLAND_PEARL_SHOP_SELL_CHECK = Button(area=(113, 22, 229, 44), color=(98, 103, 112), button=(113, 22, 229, 44), file='./assets/en/island_pearl_sell/ISLAND_PEARL_SHOP_SELL_CHECK.png')
ISLAND_PEARL_SHOP_SELL_ENTER = Button(area=(806, 413, 980, 439), color=(216, 215, 213), button=(806, 413, 980, 439), file='./assets/en/island_pearl_sell/ISLAND_PEARL_SHOP_SELL_ENTER.png')
ISLAND_PEARL_TRADE = Button(area=(226, 229, 295, 300), color=(191, 187, 183), button=(226, 229, 295, 300), file='./assets/en/island_pearl_sell/ISLAND_PEARL_TRADE.png')
ISLAND_PEARL_TRADE_BUY_CONFIRM = Button(area=(887, 552, 955, 587), color=(78, 196, 255), button=(887, 552, 955, 587), file='./assets/en/island_pearl_sell/ISLAND_PEARL_TRADE_BUY_CONFIRM.png')
ISLAND_PEARL_TRADE_SELL_CONFIRM = Button(area=(887, 552, 955, 587), color=(79, 196, 255), button=(887, 552, 955, 587), file='./assets/en/island_pearl_sell/ISLAND_PEARL_TRADE_SELL_CONFIRM.png')
OCR_ISLAND_PEARL_CURRENT_COUNT = Button(area=(960, 20, 1000, 44), color=(136, 130, 124), button=(960, 20, 1000, 44), file='./assets/en/island_pearl_sell/OCR_ISLAND_PEARL_CURRENT_COUNT.png')
OCR_ISLAND_PEARL_PRICE = Button(area=(254, 354, 305, 379), color=(111, 112, 112), button=(254, 354, 305, 379), file='./assets/en/island_pearl_sell/OCR_ISLAND_PEARL_PRICE.png')
OCR_ISLAND_PEARL_TRADE_COUNT = Button(area=(783, 360, 823, 381), color=(216, 216, 216), button=(783, 360, 823, 381), file='./assets/en/island_pearl_sell/OCR_ISLAND_PEARL_TRADE_COUNT.png')
OCR_ISLAND_PEARL_WEEKLY_PURCHASE = Button(area=(990, 69, 1210, 88), color=(156, 163, 177), button=(990, 69, 1210, 88), file='./assets/en/island_pearl_sell/OCR_ISLAND_PEARL_WEEKLY_PURCHASE.png')
TEMPLATE_ISLAND_PEARL_RANK_VISIT = Template(file='./assets/en/island_pearl_sell/TEMPLATE_ISLAND_PEARL_RANK_VISIT.png')
