from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

GAME_SETTINGS_MAIN_GOTO_SETTINGS = Button(area=(1205, 23, 1237, 50), color=(167, 169, 175), button=(1180, 18, 1264, 56), file='./assets/en/game_settings/GAME_SETTINGS_MAIN_GOTO_SETTINGS.png')
GAME_SETTINGS_OPTIONS_SELECTED = Button(area=(0, 178, 101, 269), color=(100, 83, 68), button=(0, 178, 101, 269), file='./assets/en/game_settings/GAME_SETTINGS_OPTIONS_SELECTED.png')
GAME_SETTINGS_OPTIONS_UNSELECTED = Button(area=(0, 178, 101, 269), color=(46, 51, 64), button=(0, 178, 101, 269), file='./assets/en/game_settings/GAME_SETTINGS_OPTIONS_UNSELECTED.png')
