from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

GAME_SETTINGS_MAIN_GOTO_SETTINGS = Button(area=(1205, 23, 1237, 50), color=(167, 169, 176), button=(1180, 18, 1264, 56), file='./assets/en/game_settings/GAME_SETTINGS_MAIN_GOTO_SETTINGS.gif')
GAME_SETTINGS_OPTIONS_SELECTED = Button(area=(0, 178, 101, 269), color=(98, 80, 67), button=(0, 178, 101, 269), file='./assets/en/game_settings/GAME_SETTINGS_OPTIONS_SELECTED.gif')
GAME_SETTINGS_OPTIONS_UNSELECTED = Button(area=(0, 178, 101, 269), color=(42, 47, 59), button=(0, 178, 101, 269), file='./assets/en/game_settings/GAME_SETTINGS_OPTIONS_UNSELECTED.gif')
