from __future__ import annotations

import ast
import re
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FOREIGN_ROOTS = ("assets/cn", "assets/jp", "assets/tw")
ASSET_PATTERN = re.compile(r"(?:\./)?assets/(?P<server>en|cn|jp|tw)/[^'\"\s]+")


class GlobalEnAssetTests(unittest.TestCase):
    def test_only_global_asset_root_exists(self) -> None:
        self.assertTrue((ROOT / "assets/en").is_dir())
        for root in FOREIGN_ROOTS:
            self.assertFalse((ROOT / root).exists(), root)

    def test_generator_discovers_only_assets_en(self) -> None:
        source = (ROOT / "dev_tools/button_extract.py").read_text(encoding="utf-8")
        self.assertIn("CANONICAL_SERVER = 'en'", source)
        self.assertNotIn("VALID_SERVER", source)
        self.assertNotIn("use cn server assets", source)
        for root in FOREIGN_ROOTS:
            self.assertNotIn(root, source)

    def test_generated_outputs_are_scalar_global_paths(self) -> None:
        generated = []
        for path in sorted((ROOT / "module").glob("*/assets.py")):
            source = path.read_text(encoding="utf-8")
            if "automatically generated by dev_tools/button_extract.py" not in source:
                continue
            generated.append(path)
            tree = ast.parse(source, str(path))
            for node in ast.walk(tree):
                if isinstance(node, ast.Dict):
                    keys = {
                        key.value for key in node.keys
                        if isinstance(key, ast.Constant) and isinstance(key.value, str)
                    }
                    self.assertTrue(keys.isdisjoint({"cn", "en", "jp", "tw"}), path)
            for match in ASSET_PATTERN.finditer(source):
                self.assertEqual(match.group("server"), "en", path)
                raw = match.group(0).removeprefix("./")
                self.assertTrue((ROOT / raw).is_file(), raw)
        self.assertTrue(generated)


if __name__ == "__main__":
    unittest.main()
