from __future__ import annotations

import ast
import io
import re
import tokenize
from pathlib import Path

from dev_tools.runtime_russianization_audit import audit_source

ROOT = Path(__file__).resolve().parents[1]
CJK_RE = re.compile(r"[\u3400-\u9fff\uf900-\ufaff]")
CYRILLIC_RE = re.compile(r"[А-Яа-яЁё]")
LATIN_WORD_RE = re.compile(r"\b[A-Za-z]{2,}\b")
URL_RE = re.compile(r"https?://\S+")
INLINE_CODE_RE = re.compile(r"``[^`]+``|`[^`]+`")
FILE_TOKEN_RE = re.compile(r"\b[A-Za-z0-9_.~/-]+\.[A-Za-z0-9]+\b")
DOTTED_IDENTIFIER_RE = re.compile(r"\b[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)+\b")
TECHNICAL_DIRECTIVE_PREFIXES = (
    "noqa",
    "type:",
    "fmt:",
    "pragma:",
    "pylint:",
    "ruff:",
    "mypy:",
    "pyright:",
)
GENERATED_ASSET_BOILERPLATE = {
    "This file was automatically generated by dev_tools/button_extract.py.",
    "Don't modify it manually.",
}

# Production Python, затронутый PR #105. Raw data/fixtures, тесты и dev_tools
# намеренно не входят в языковую политику production-кода.
TOUCHED_PRODUCTION = (
    "campaign/__init__.py",
    "campaign/generated_event/__init__.py",
    "campaign/generated_event/en_51101/__init__.py",
    "campaign/generated_event/en_51101/a1.py",
    "campaign/generated_event/en_51101/a2.py",
    "campaign/generated_event/en_51101/a3.py",
    "campaign/generated_event/en_51101/b1.py",
    "campaign/generated_event/en_51101/b2.py",
    "campaign/generated_event/en_51101/b3.py",
    "campaign/generated_event/en_51101/c1.py",
    "campaign/generated_event/en_51101/c2.py",
    "campaign/generated_event/en_51101/c3.py",
    "campaign/generated_event/en_51101/d1.py",
    "campaign/generated_event/en_51101/d2.py",
    "campaign/generated_event/en_51101/d3.py",
    "campaign/generated_event/en_51101/sp.py",
    "module/event_datamine/__init__.py",
    "module/event_datamine/artifact.py",
    "module/event_datamine/assets.py",
    "module/event_datamine/campaign_selector.py",
    "module/event_datamine/compiler.py",
    "module/event_datamine/discovery.py",
    "module/event_datamine/generator.py",
    "module/event_datamine/map_compiler.py",
    "module/event_datamine/model.py",
    "module/event_datamine/patches.py",
    "module/event_datamine/registry.py",
    "module/event_datamine/runtime_policy.py",
    "module/event_datamine/runtime_semantics.py",
    "module/event_datamine/source.py",
    "module/event_datamine/supplemental.py",
    "module/event_datamine/supplemental_projection.py",
    "module/event_datamine/supplemental_resolver.py",
    "module/event_datamine/supplemental_verify.py",
    "module/log_res/log_res.py",
    "module/logger.py",
    "module/map/map_fleet_preparation.py",
    "module/map/map_operation.py",
    "module/map_detection/utils_assets.py",
    "module/retire/retirement.py",
    "module/shop_event/clerk.py",
    "module/shop_event/item.py",
    "module/shop_event/notification_policy.py",
    "module/shop_event/selector.py",
    "module/shop_event/shop_event.py",
    "module/shop_event/ui.py",
    "module/statistics/item.py",
    "module/template/assets.py",
    "module/webui/app.py",
    "module/webui/app_event_datamine.py",
    "module/webui/app_event_general_presentation.py",
    "module/webui/app_event_general_v2.py",
    "module/webui/app_event_layout.py",
    "module/webui/app_event_planner.py",
    "module/webui/app_event_shop_live.py",
    "module/webui/app_event_shop_safety.py",
    "module/webui/app_event_shop_v2.py",
    "module/webui/event_assets.py",
    "module/webui/event_currency.py",
    "module/webui/event_observation.py",
    "module/webui/event_observation_update.py",
    "module/webui/event_profiles.py",
    "module/webui/event_shop_observation.py",
    "module/webui/event_shop_priority.py",
    "module/webui/event_source.py",
    "module/webui/state_lock.py",
)


def _comments(source: str):
    for token in tokenize.generate_tokens(io.StringIO(source).readline):
        if token.type == tokenize.COMMENT:
            yield token.start[0], token.string.lstrip("# ")


def _docstrings(source: str, path: str):
    tree = ast.parse(source, path)
    nodes = [tree]
    nodes.extend(
        node
        for node in ast.walk(tree)
        if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef))
    )
    for node in nodes:
        text = ast.get_docstring(node, clean=False)
        if text:
            yield getattr(node, "lineno", 1), text


def _looks_like_english_prose(text: str) -> bool:
    stripped = text.strip()
    if not stripped or CYRILLIC_RE.search(stripped):
        return False
    if stripped.lower().startswith(TECHNICAL_DIRECTIVE_PREFIXES):
        return False
    cleaned = URL_RE.sub("", stripped)
    cleaned = INLINE_CODE_RE.sub("", cleaned)
    cleaned = FILE_TOKEN_RE.sub("", cleaned)
    cleaned = DOTTED_IDENTIFIER_RE.sub("", cleaned)
    words = LATIN_WORD_RE.findall(cleaned)
    # Короткие технические маркеры и идентификаторы не считаются prose.
    # Три и более обычных латинских слов уже требуют русского пояснения.
    return len(words) >= 3


def _is_generated_asset_boilerplate(relative: str, kind: str, text: str) -> bool:
    """Исключить только стандартный машинный заголовок generated assets.py."""
    return (
        kind == "comment"
        and relative.startswith("module/")
        and relative.endswith("/assets.py")
        and text.strip() in GENERATED_ASSET_BOILERPLATE
    )


def _language_findings():
    findings = []
    for relative in TOUCHED_PRODUCTION:
        path = ROOT / relative
        assert path.is_file(), relative
        source = path.read_text(encoding="utf-8")
        for kind, entries in (
            ("comment", _comments(source)),
            ("docstring", _docstrings(source, relative)),
        ):
            for line, text in entries:
                if _is_generated_asset_boilerplate(relative, kind, text):
                    continue
                if CJK_RE.search(text):
                    findings.append(f"{relative}:{line}: {kind} содержит CJK")
                elif _looks_like_english_prose(text):
                    findings.append(
                        f"{relative}:{line}: {kind} содержит английскую prose без русского текста: {text!r}"
                    )
    return findings


def test_touched_production_comments_and_docstrings_follow_russian_policy():
    assert len(TOUCHED_PRODUCTION) == len(set(TOUCHED_PRODUCTION))
    findings = _language_findings()
    assert not findings, "\n".join(findings)


def test_touched_production_runtime_sinks_follow_russian_policy():
    blockers = []
    for relative in TOUCHED_PRODUCTION:
        source = (ROOT / relative).read_text(encoding="utf-8")
        blockers.extend(audit_source(source, relative).blockers)
    assert not blockers, "\n".join(blockers)
