from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BACK_ARROW_WHITE = Button(area=(54, 30, 69, 53), color=(199, 199, 199), button=(54, 30, 69, 53), file='./assets/en/ui_white/BACK_ARROW_WHITE.png')
GOTO_MAIN_WHITE = Button(area=(1211, 24, 1239, 47), color=(151, 151, 152), button=(1211, 24, 1239, 47), file='./assets/en/ui_white/GOTO_MAIN_WHITE.png')
MAIL_CHECK = Button(area=(141, 21, 181, 41), color=(101, 109, 122), button=(141, 21, 181, 41), file='./assets/en/ui_white/MAIL_CHECK.png')
MAIL_ENTER_WHITE = Button(area=(1018, 22, 1085, 52), color=(196, 194, 194), button=(1018, 22, 1085, 52), file='./assets/en/ui_white/MAIL_ENTER_WHITE.png')
MAIN_GOTO_BUILD_WHITE = Button(area=(959, 657, 1104, 703), color=(226, 220, 222), button=(959, 657, 1104, 703), file='./assets/en/ui_white/MAIN_GOTO_BUILD_WHITE.png')
MAIN_GOTO_CAMPAIGN_WHITE = Button(area=(1126, 549, 1219, 577), color=(156, 164, 165), button=(1123, 439, 1260, 580), file='./assets/en/ui_white/MAIN_GOTO_CAMPAIGN_WHITE.png')
MAIN_GOTO_DOCK_WHITE = Button(area=(176, 656, 322, 703), color=(226, 226, 230), button=(176, 656, 322, 703), file='./assets/en/ui_white/MAIN_GOTO_DOCK_WHITE.png')
MAIN_GOTO_DORMMENU_WHITE = Button(area=(490, 657, 635, 703), color=(218, 216, 217), button=(490, 657, 635, 703), file='./assets/en/ui_white/MAIN_GOTO_DORMMENU_WHITE.png')
MAIN_GOTO_EVENT_LIST_WHITE = Button(area=(1179, 82, 1260, 161), color=(148, 156, 184), button=(1179, 82, 1260, 161), file='./assets/en/ui_white/MAIN_GOTO_EVENT_LIST_WHITE.png')
MAIN_GOTO_FLEET_WHITE = Button(area=(1024, 436, 1099, 580), color=(218, 217, 218), button=(1024, 436, 1099, 580), file='./assets/en/ui_white/MAIN_GOTO_FLEET_WHITE.png')
MAIN_GOTO_GUILD_WHITE = Button(area=(1115, 657, 1262, 703), color=(217, 215, 216), button=(1115, 657, 1262, 703), file='./assets/en/ui_white/MAIN_GOTO_GUILD_WHITE.png')
MAIN_GOTO_MEMORIES_WHITE = Button(area=(1125, 546, 1195, 579), color=(255, 152, 191), button=(1125, 546, 1195, 579), file='./assets/en/ui_white/MAIN_GOTO_MEMORIES_WHITE.png')
MAIN_GOTO_MISSION_WHITE = Button(area=(803, 656, 948, 703), color=(210, 207, 207), button=(803, 656, 948, 703), file='./assets/en/ui_white/MAIN_GOTO_MISSION_WHITE.png')
MAIN_GOTO_RAID_WHITE = Button(area=(1071, 83, 1151, 159), color=(105, 95, 94), button=(1071, 83, 1151, 159), file='./assets/en/ui_white/MAIN_GOTO_RAID_WHITE.png')
MAIN_GOTO_RESHMENU_WHITE = Button(area=(646, 656, 792, 703), color=(224, 224, 225), button=(646, 656, 792, 703), file='./assets/en/ui_white/MAIN_GOTO_RESHMENU_WHITE.png')
MAIN_GOTO_REWARD_WHITE = Button(area=(11, 216, 31, 253), color=(105, 115, 162), button=(11, 216, 31, 253), file='./assets/en/ui_white/MAIN_GOTO_REWARD_WHITE.png')
MAIN_GOTO_SHOP_WHITE = Button(area=(18, 656, 165, 703), color=(232, 220, 204), button=(18, 656, 165, 703), file='./assets/en/ui_white/MAIN_GOTO_SHOP_WHITE.png')
MAIN_GOTO_STORAGE_WHITE = Button(area=(331, 657, 478, 703), color=(214, 215, 216), button=(331, 657, 478, 703), file='./assets/en/ui_white/MAIN_GOTO_STORAGE_WHITE.png')
MAIN_TAB_SWITCH_WHITE = Button(area=(966, 548, 999, 582), color=(89, 93, 108), button=(966, 548, 999, 582), file='./assets/en/ui_white/MAIN_TAB_SWITCH_WHITE.png')
MISSION_NOTICE_WHITE = Button(area=(923, 657, 947, 671), color=(227, 168, 159), button=(923, 657, 947, 671), file='./assets/en/ui_white/MISSION_NOTICE_WHITE.png')
POPUP_CANCEL_WHITE = Button(area=(471, 492, 547, 513), color=(205, 206, 205), button=(471, 492, 547, 513), file='./assets/en/ui_white/POPUP_CANCEL_WHITE.png')
POPUP_CONFIRM_WHITE = Button(area=(727, 495, 810, 515), color=(107, 207, 255), button=(727, 495, 810, 515), file='./assets/en/ui_white/POPUP_CONFIRM_WHITE.png')
POPUP_CONFIRM_WHITE_BATTLEPASS = Button(area=(721, 492, 818, 510), color=(149, 221, 255), button=(721, 492, 818, 510), file='./assets/en/ui_white/POPUP_CONFIRM_WHITE_BATTLEPASS.png')
POPUP_SINGLE_WHITE = Button(area=(623, 493, 668, 515), color=(131, 215, 255), button=(623, 493, 668, 515), file='./assets/en/ui_white/POPUP_SINGLE_WHITE.png')
REWARD_1_WHITE = Button(area=(411, 283, 523, 300), color=(255, 212, 150), button=(411, 283, 523, 300), file='./assets/en/ui_white/REWARD_1_WHITE.png')
REWARD_2_WHITE = Button(area=(411, 425, 523, 442), color=(255, 212, 146), button=(411, 425, 523, 442), file='./assets/en/ui_white/REWARD_2_WHITE.png')
REWARD_GOTO_COMMISSION_WHITE = Button(area=(420, 283, 512, 300), color=(149, 220, 255), button=(420, 283, 512, 300), file='./assets/en/ui_white/REWARD_GOTO_COMMISSION_WHITE.png')
REWARD_GOTO_TACTICAL_WHITE = Button(area=(420, 425, 512, 443), color=(145, 219, 255), button=(420, 425, 512, 443), file='./assets/en/ui_white/REWARD_GOTO_TACTICAL_WHITE.png')
