"""Публичный application boundary durable notifications."""

from module.application.errors import NotificationValidationError
from module.application.notifications.channels import (
    NotificationChannel,
    NotificationChannelCatalog,
)
from module.application.notifications.dispatcher import NotificationDispatcher
from module.application.notifications.models import (
    ChannelCapabilities,
    ClaimedDelivery,
    DeliveryResult,
    DeliveryResultClass,
    DeliveryState,
    DeliveryUpdate,
    DispatchReport,
    HandoverNotificationOutcome,
    HandoverNotificationResult,
    HandoverPreemptionPayload,
    NotificationAttribute,
    NotificationCorrelation,
    NotificationDeliveryPlan,
    NotificationEvent,
    NotificationEventProjection,
    NotificationPolicy,
    NotificationPolicySnapshot,
    NotificationRule,
    NotificationRuleMatcher,
    NotificationSensitivity,
    NotificationSeverity,
    NotificationStoredAttempt,
    NotificationStoredDelivery,
    NotificationStoredEvent,
    NotificationSubject,
    PolicyAction,
    PolicyDecision,
    PolicyState,
    PreparedDelivery,
    PublishResult,
    PublishStatus,
    ReceiptStrength,
    RenderedSnapshot,
)
from module.application.notifications.policy import (
    NotificationPolicyResolver,
    default_notification_policy,
)
from module.application.notifications.ports import (
    NotificationRepository,
    NotificationUnitOfWork,
)
from module.application.notifications.registry import (
    DeferredNotificationPayload,
    NotificationDescriptor,
    NotificationRegistry,
    build_default_registry,
    default_registry,
)
from module.application.notifications.rendering import (
    HandoverPreemptionRenderer,
    NotificationRenderer,
    NotificationRendererCatalog,
    build_default_renderer_catalog,
)
from module.application.notifications.service import (
    NotificationPublisher,
)
from module.application.notifications.state import (
    RetryPolicy,
    expired_lease_update,
    transition_for_result,
)

__all__ = [
    "ChannelCapabilities",
    "ClaimedDelivery",
    "DeferredNotificationPayload",
    "DeliveryResult",
    "DeliveryResultClass",
    "DeliveryState",
    "DeliveryUpdate",
    "DispatchReport",
    "HandoverNotificationOutcome",
    "HandoverNotificationResult",
    "HandoverPreemptionPayload",
    "HandoverPreemptionRenderer",
    "NotificationAttribute",
    "NotificationChannel",
    "NotificationChannelCatalog",
    "NotificationCorrelation",
    "NotificationDeliveryPlan",
    "NotificationDescriptor",
    "NotificationDispatcher",
    "NotificationEvent",
    "NotificationEventProjection",
    "NotificationPolicy",
    "NotificationPolicyResolver",
    "NotificationPolicySnapshot",
    "NotificationPublisher",
    "NotificationRegistry",
    "NotificationRenderer",
    "NotificationRendererCatalog",
    "NotificationRepository",
    "NotificationRule",
    "NotificationRuleMatcher",
    "NotificationSensitivity",
    "NotificationSeverity",
    "NotificationStoredAttempt",
    "NotificationStoredDelivery",
    "NotificationStoredEvent",
    "NotificationSubject",
    "NotificationUnitOfWork",
    "NotificationValidationError",
    "PolicyAction",
    "PolicyDecision",
    "PolicyState",
    "PreparedDelivery",
    "PublishResult",
    "PublishStatus",
    "ReceiptStrength",
    "RenderedSnapshot",
    "RetryPolicy",
    "build_default_registry",
    "build_default_renderer_catalog",
    "default_registry",
    "default_notification_policy",
    "expired_lease_update",
    "transition_for_result",
]
