from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BUILD_CUBE_COUNT = Button(area=(872, 106, 925, 137), color=(82, 84, 95), button=(872, 106, 925, 137), file='./assets/en/gacha/BUILD_CUBE_COUNT.png')
BUILD_FINISH_ORDERS = Button(area=(1122, 99, 1261, 140), color=(175, 132, 76), button=(1122, 99, 1261, 140), file='./assets/en/gacha/BUILD_FINISH_ORDERS.png')
BUILD_FINISH_RESULTS = Button(area=(550, 187, 737, 219), color=(158, 187, 234), button=(550, 187, 737, 219), file='./assets/en/gacha/BUILD_FINISH_RESULTS.png')
BUILD_MINUS = Button(area=(525, 255, 565, 293), color=(81, 132, 200), button=(525, 255, 565, 293), file='./assets/en/gacha/BUILD_MINUS.png')
BUILD_PLUS = Button(area=(704, 255, 744, 293), color=(86, 135, 204), button=(704, 255, 744, 293), file='./assets/en/gacha/BUILD_PLUS.png')
BUILD_QUEUE_EMPTY = Button(area=(639, 362, 700, 409), color=(157, 151, 152), button=(639, 362, 700, 409), file='./assets/en/gacha/BUILD_QUEUE_EMPTY.png')
BUILD_SUBMIT_COUNT = Button(area=(604, 257, 668, 291), color=(75, 78, 90), button=(604, 257, 668, 291), file='./assets/en/gacha/BUILD_SUBMIT_COUNT.png')
BUILD_SUBMIT_ORDERS = Button(area=(1033, 603, 1223, 656), color=(236, 188, 115), button=(1033, 603, 1223, 656), file='./assets/en/gacha/BUILD_SUBMIT_ORDERS.png')
BUILD_SUBMIT_WW_COUNT = Button(area=(650, 257, 714, 291), color=(75, 80, 90), button=(650, 257, 714, 291), file='./assets/en/gacha/BUILD_SUBMIT_WW_COUNT.png')
BUILD_SUBMIT_WW_ORDERS = Button(area=(504, 578, 694, 618), color=(231, 218, 92), button=(504, 578, 694, 618), file='./assets/en/gacha/BUILD_SUBMIT_WW_ORDERS.png')
BUILD_TICKET_CHECK = Button(area=(640, 110, 677, 131), color=(56, 107, 211), button=(640, 110, 677, 131), file='./assets/en/gacha/BUILD_TICKET_CHECK.png')
BUILD_TICKET_COUNT = Button(area=(681, 105, 788, 138), color=(47, 50, 62), button=(681, 105, 788, 138), file='./assets/en/gacha/BUILD_TICKET_COUNT.png')
BUILD_WW_CHECK = Button(area=(602, 603, 784, 650), color=(99, 116, 137), button=(602, 603, 784, 650), file='./assets/en/gacha/BUILD_WW_CHECK.png')
SHOP_MEDAL_CHECK = Button(area=(573, 102, 604, 145), color=(93, 102, 118), button=(573, 102, 604, 145), file='./assets/en/gacha/SHOP_MEDAL_CHECK.png')
