from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ATTACKER_HP_AREA = Button(area=(271, 43, 586, 58), color=(239, 51, 15), button=(271, 43, 586, 58), file='./assets/en/exercise/ATTACKER_HP_AREA.png')
ATTACKER_HP_AREA_New = Button(area=(266, 40, 592, 49), color=(232, 82, 45), button=(266, 40, 592, 49), file='./assets/en/exercise/ATTACKER_HP_AREA_New.png')
CLICK_SAFE_AREA = Button(area=(1215, 637, 1260, 686), color=(253, 180, 75), button=(1215, 637, 1260, 686), file='./assets/en/exercise/CLICK_SAFE_AREA.png')
DEFENDER_HP_AREA = Button(area=(691, 43, 1004, 58), color=(239, 51, 15), button=(691, 43, 1004, 58), file='./assets/en/exercise/DEFENDER_HP_AREA.png')
DEFENDER_HP_AREA_New = Button(area=(692, 40, 1019, 49), color=(231, 80, 45), button=(692, 40, 1019, 49), file='./assets/en/exercise/DEFENDER_HP_AREA_New.png')
EQUIP_EDIT_ACTIVE = Button(area=(50, 607, 247, 670), color=(186, 157, 105), button=(50, 607, 247, 670), file='./assets/en/exercise/EQUIP_EDIT_ACTIVE.png')
EQUIP_EDIT_INACTIVE = Button(area=(50, 607, 247, 670), color=(88, 111, 156), button=(50, 607, 247, 670), file='./assets/en/exercise/EQUIP_EDIT_INACTIVE.png')
EQUIP_ENTER = Button(area=(432, 283, 442, 293), color=(207, 206, 206), button=(432, 283, 442, 293), file='./assets/en/exercise/EQUIP_ENTER.png')
EXERCISE_PREPARATION = Button(area=(541, 537, 743, 601), color=(234, 182, 102), button=(541, 537, 743, 601), file='./assets/en/exercise/EXERCISE_PREPARATION.png')
NEW_OPPONENT = Button(area=(1064, 339, 1205, 384), color=(128, 165, 221), button=(1064, 339, 1205, 384), file='./assets/en/exercise/NEW_OPPONENT.png')
OCR_EXERCISE_REMAIN = Button(area=(1153, 140, 1178, 165), color=(96, 132, 113), button=(1153, 140, 1178, 165), file='./assets/en/exercise/OCR_EXERCISE_REMAIN.png')
OCR_EXERCISE_TIME_REMAIN = Button(area=(1088, 105, 1208, 128), color=(124, 133, 171), button=(1088, 105, 1208, 128), file='./assets/en/exercise/OCR_EXERCISE_TIME_REMAIN.png')
OCR_PERIOD_REMAIN = Button(area=(1089, 105, 1209, 129), color=(125, 133, 169), button=(1089, 105, 1209, 129), file='./assets/en/exercise/OCR_PERIOD_REMAIN.png')
OPPONENT_1 = Button(area=(102, 76, 318, 381), color=(100, 115, 134), button=(102, 76, 318, 381), file='./assets/en/exercise/OPPONENT_1.png')
OPPONENT_2 = Button(area=(348, 77, 562, 381), color=(105, 122, 150), button=(348, 77, 562, 381), file='./assets/en/exercise/OPPONENT_2.png')
OPPONENT_3 = Button(area=(592, 77, 806, 381), color=(105, 129, 156), button=(592, 77, 806, 381), file='./assets/en/exercise/OPPONENT_3.png')
OPPONENT_4 = Button(area=(836, 77, 1050, 381), color=(112, 127, 152), button=(836, 77, 1050, 381), file='./assets/en/exercise/OPPONENT_4.png')
