"""Транспортно-независимый прикладной слой AzurPilot.

Импорт пакета намеренно не создаёт runtime-объекты и не читает конфигурацию.
Legacy-адаптеры подключаются вызывающей стороной явно.
"""

from module.application.errors import (
    ApplicationError,
    IncompatibleSchemaError,
    InvalidRequestError,
    ResourceNotFoundError,
    ServiceUnavailableError,
    StorageAuthenticationError,
    StorageConfigurationError,
    StorageConflictError,
    StorageError,
    StorageInvalidDataError,
    StorageUnavailableError,
)
from module.application.models import (
    InstanceReference,
    InstanceStatus,
    RuntimeState,
    TaskArgumentMetadata,
    TaskGroupMetadata,
    TaskMetadata,
    TaskOption,
    TaskSummary,
)
from module.application.fleet_autoscan import (
    FLEET_AUTOSCAN_SOURCE_DAILY,
    FLEET_AUTOSCAN_SOURCE_EVERY_START,
    FleetAutoScanConfig,
    FleetAutoScanCoordinator,
    FleetAutoScanExecution,
    FleetAutoScanMode,
    FleetAutoScanPolicy,
    FleetAutoScanRetryPolicy,
)
from module.application.fleet_state import (
    FleetRefreshPolicy,
    FleetScanAttempt,
    FleetScanBatchResult,
    FleetScanRun,
    FleetScanRunStatus,
    FleetScanService,
    FleetStateObservation,
    FleetStateRequest,
    FleetStateResult,
    FleetStateService,
)
from module.application.services import InstanceQueryService, TaskCatalogService
from module.application.migration_service import MigrationService, finalize_rehearsal
from module.application.storage_models import (
    CommissionIncome,
    CommissionItem,
    ImportBatch,
    ImportBatchStatus,
    InstanceIdentity,
    MonthlyAggregate,
    MonthlyMetric,
    OpsiItemEvent,
    ResourceSnapshot,
    StorageHealth,
    StorageHealthState,
)

__all__ = (
    "ApplicationError",
    "CommissionIncome",
    "CommissionItem",
    "FLEET_AUTOSCAN_SOURCE_DAILY",
    "FLEET_AUTOSCAN_SOURCE_EVERY_START",
    "FleetAutoScanConfig",
    "FleetAutoScanCoordinator",
    "FleetAutoScanExecution",
    "FleetAutoScanMode",
    "FleetAutoScanPolicy",
    "FleetAutoScanRetryPolicy",
    "FleetRefreshPolicy",
    "FleetScanAttempt",
    "FleetScanBatchResult",
    "FleetScanRun",
    "FleetScanRunStatus",
    "FleetScanService",
    "FleetStateObservation",
    "FleetStateRequest",
    "FleetStateResult",
    "FleetStateService",
    "ImportBatch",
    "ImportBatchStatus",
    "IncompatibleSchemaError",
    "InstanceIdentity",
    "InstanceQueryService",
    "InstanceReference",
    "InstanceStatus",
    "InvalidRequestError",
    "MonthlyAggregate",
    "MonthlyMetric",
    "MigrationService",
    "OpsiItemEvent",
    "ResourceNotFoundError",
    "ResourceSnapshot",
    "RuntimeState",
    "ServiceUnavailableError",
    "StorageAuthenticationError",
    "StorageConfigurationError",
    "StorageConflictError",
    "StorageError",
    "StorageHealth",
    "StorageHealthState",
    "StorageInvalidDataError",
    "StorageUnavailableError",
    "TaskArgumentMetadata",
    "TaskCatalogService",
    "TaskGroupMetadata",
    "TaskMetadata",
    "TaskOption",
    "TaskSummary",
    "finalize_rehearsal",
)
