"""основа хранения v1

Revision ID: 0001_storage_foundation
Revises:
Create Date: 2026-08-23 07:01:03.961161
"""

import os
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateSchema, DropSchema

revision: str = "0001_storage_foundation"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Применить migration."""
    op.execute(CreateSchema("azurpilot"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_instance",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_instance")),
        sa.UniqueConstraint("name", name=op.f("uq_app_instance_name")),
        schema="azurpilot",
    )
    op.create_table(
        "import_batch",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("source_kind", sa.String(length=64), nullable=False),
        sa.Column("source_digest", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("record_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("imported_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("conflict_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("quarantine_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "source_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_import_batch_source_digest_sha256"),
        ),
        sa.CheckConstraint(
            "status IN ('started', 'completed', 'failed', 'conflict')",
            name=op.f("ck_import_batch_status_allowed"),
        ),
        sa.CheckConstraint(
            "record_count >= 0 AND imported_count >= 0 AND conflict_count >= 0 AND quarantine_count >= 0",
            name=op.f("ck_import_batch_counts_nonnegative"),
        ),
        sa.CheckConstraint(
            "imported_count + conflict_count + quarantine_count <= record_count",
            name=op.f("ck_import_batch_counts_within_record_count"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batch")),
        sa.UniqueConstraint(
            "idempotency_key", name=op.f("uq_import_batch_idempotency_key")
        ),
        schema="azurpilot",
    )
    op.create_table(
        "ap_notification_state",
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("last_ap", sa.BigInteger(), nullable=False),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("legacy_timestamp_text", sa.String(length=64), nullable=True),
        sa.Column("legacy_timezone", sa.String(length=64), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "last_ap >= 0", name=op.f("ck_ap_notification_state_last_ap_nonnegative")
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_ap_notification_state_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["azurpilot.app_instance.id"],
            name=op.f("fk_ap_notification_state_instance_id_app_instance"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("instance_id", name=op.f("pk_ap_notification_state")),
        schema="azurpilot",
    )
    op.create_table(
        "cl1_ap_purchase_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("payload_digest", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("legacy_timestamp_text", sa.String(length=64), nullable=True),
        sa.Column("legacy_timezone", sa.String(length=64), nullable=True),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("base_amount", sa.BigInteger(), nullable=False),
        sa.Column("purchase_count", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "payload_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_cl1_ap_purchase_event_payload_digest_sha256"),
        ),
        sa.CheckConstraint(
            "amount >= 0 AND base_amount >= 0 AND purchase_count >= 0",
            name=op.f("ck_cl1_ap_purchase_event_values_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["azurpilot.app_instance.id"],
            name=op.f("fk_cl1_ap_purchase_event_instance_id_app_instance"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cl1_ap_purchase_event")),
        sa.UniqueConstraint(
            "idempotency_key", name=op.f("uq_cl1_ap_purchase_event_idempotency_key")
        ),
        schema="azurpilot",
    )
    op.create_index(
        "ix_cl1_ap_purchase_instance_observed",
        "cl1_ap_purchase_event",
        ["instance_id", sa.literal_column("observed_at DESC NULLS LAST")],
        unique=False,
        schema="azurpilot",
    )
    op.create_table(
        "cl1_ap_snapshot",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("payload_digest", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("legacy_timestamp_text", sa.String(length=64), nullable=True),
        sa.Column("legacy_timezone", sa.String(length=64), nullable=True),
        sa.Column("ap", sa.BigInteger(), nullable=False),
        sa.Column("ap_total", sa.BigInteger(), nullable=True),
        sa.Column("asset", sa.BigInteger(), nullable=True),
        sa.Column("yellow_coin", sa.BigInteger(), nullable=True),
        sa.Column("distance", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "payload_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_cl1_ap_snapshot_payload_digest_sha256"),
        ),
        sa.CheckConstraint(
            "ap >= 0 AND (ap_total IS NULL OR ap_total >= 0) AND (asset IS NULL OR asset >= 0) AND (yellow_coin IS NULL OR yellow_coin >= 0) AND (distance IS NULL OR distance >= 0)",
            name=op.f("ck_cl1_ap_snapshot_values_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["azurpilot.app_instance.id"],
            name=op.f("fk_cl1_ap_snapshot_instance_id_app_instance"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cl1_ap_snapshot")),
        sa.UniqueConstraint(
            "idempotency_key", name=op.f("uq_cl1_ap_snapshot_idempotency_key")
        ),
        schema="azurpilot",
    )
    op.create_index(
        "ix_cl1_ap_snapshot_instance_observed",
        "cl1_ap_snapshot",
        ["instance_id", sa.literal_column("observed_at DESC NULLS LAST")],
        unique=False,
        schema="azurpilot",
    )
    op.create_table(
        "cl1_currency_snapshot",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("payload_digest", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("legacy_timestamp_text", sa.String(length=64), nullable=True),
        sa.Column("legacy_timezone", sa.String(length=64), nullable=True),
        sa.Column("currency_code", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "payload_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_cl1_currency_snapshot_payload_digest_sha256"),
        ),
        sa.CheckConstraint(
            "amount >= 0", name=op.f("ck_cl1_currency_snapshot_amount_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["azurpilot.app_instance.id"],
            name=op.f("fk_cl1_currency_snapshot_instance_id_app_instance"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cl1_currency_snapshot")),
        sa.UniqueConstraint(
            "idempotency_key", name=op.f("uq_cl1_currency_snapshot_idempotency_key")
        ),
        schema="azurpilot",
    )
    op.create_index(
        "ix_cl1_currency_instance_code_observed",
        "cl1_currency_snapshot",
        [
            "instance_id",
            "currency_code",
            sa.literal_column("observed_at DESC NULLS LAST"),
        ],
        unique=False,
        schema="azurpilot",
    )
    op.create_table(
        "commission_income_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("payload_digest", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("legacy_timestamp_text", sa.String(length=64), nullable=True),
        sa.Column("legacy_timezone", sa.String(length=64), nullable=True),
        sa.Column("commission_count", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "payload_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_commission_income_event_payload_digest_sha256"),
        ),
        sa.CheckConstraint(
            "commission_count > 0",
            name=op.f("ck_commission_income_event_commission_count_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["azurpilot.app_instance.id"],
            name=op.f("fk_commission_income_event_instance_id_app_instance"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commission_income_event")),
        sa.UniqueConstraint(
            "idempotency_key", name=op.f("uq_commission_income_event_idempotency_key")
        ),
        schema="azurpilot",
    )
    op.create_index(
        "ix_commission_income_instance_observed",
        "commission_income_event",
        ["instance_id", sa.literal_column("observed_at DESC NULLS LAST")],
        unique=False,
        schema="azurpilot",
    )
    op.create_table(
        "import_record",
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("source_object", sa.String(length=128), nullable=False),
        sa.Column("source_locator", sa.String(length=256), nullable=False),
        sa.Column("payload_digest", sa.String(length=64), nullable=False),
        sa.Column("disposition", sa.String(length=32), nullable=False),
        sa.Column("target_table", sa.String(length=63), nullable=True),
        sa.Column("target_key", sa.String(length=128), nullable=True),
        sa.Column(
            "quarantine_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.CheckConstraint(
            "payload_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_import_record_payload_digest_sha256"),
        ),
        sa.CheckConstraint(
            "quarantine_metadata IS NULL OR octet_length(quarantine_metadata::text) <= 8192",
            name=op.f("ck_import_record_quarantine_metadata_bounded"),
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["azurpilot.import_batch.id"],
            name=op.f("fk_import_record_batch_id_import_batch"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "batch_id", "source_object", "source_locator", name=op.f("pk_import_record")
        ),
        schema="azurpilot",
    )
    op.create_table(
        "legacy_instance_alias",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("alias_kind", sa.String(length=32), nullable=False),
        sa.Column("alias_digest", sa.String(length=64), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("source_provenance", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "alias_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_legacy_instance_alias_alias_digest_sha256"),
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["azurpilot.app_instance.id"],
            name=op.f("fk_legacy_instance_alias_instance_id_app_instance"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legacy_instance_alias")),
        sa.UniqueConstraint(
            "alias_kind",
            "alias_digest",
            name=op.f("uq_legacy_instance_alias_alias_kind_alias_digest"),
        ),
        schema="azurpilot",
    )
    op.create_index(
        "ix_legacy_instance_alias_instance_id",
        "legacy_instance_alias",
        ["instance_id"],
        unique=False,
        schema="azurpilot",
    )
    op.create_table(
        "meow_hazard_aggregate",
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("hazard_level", sa.Integer(), nullable=False),
        sa.Column("raw_battle_count", sa.BigInteger(), nullable=False),
        sa.Column(
            "effective_rounds", sa.Numeric(precision=18, scale=6), nullable=False
        ),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "EXTRACT(DAY FROM month) = 1",
            name=op.f("ck_meow_hazard_aggregate_month_first_day"),
        ),
        sa.CheckConstraint(
            "hazard_level BETWEEN 1 AND 6",
            name=op.f("ck_meow_hazard_aggregate_hazard_level_range"),
        ),
        sa.CheckConstraint(
            "raw_battle_count >= 0 AND effective_rounds >= 0",
            name=op.f("ck_meow_hazard_aggregate_counts_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["azurpilot.app_instance.id"],
            name=op.f("fk_meow_hazard_aggregate_instance_id_app_instance"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "instance_id",
            "month",
            "hazard_level",
            name=op.f("pk_meow_hazard_aggregate"),
        ),
        schema="azurpilot",
    )
    op.create_table(
        "meow_timing_sample",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("payload_digest", sa.String(length=64), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("legacy_timestamp_text", sa.String(length=64), nullable=True),
        sa.Column("legacy_timezone", sa.String(length=64), nullable=True),
        sa.Column("sample_kind", sa.String(length=16), nullable=False),
        sa.Column(
            "duration_seconds", sa.Numeric(precision=18, scale=6), nullable=False
        ),
        sa.Column("hazard_level", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "EXTRACT(DAY FROM month) = 1",
            name=op.f("ck_meow_timing_sample_month_first_day"),
        ),
        sa.CheckConstraint(
            "payload_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_meow_timing_sample_payload_digest_sha256"),
        ),
        sa.CheckConstraint(
            "sample_kind IN ('battle', 'round')",
            name=op.f("ck_meow_timing_sample_sample_kind_allowed"),
        ),
        sa.CheckConstraint(
            "duration_seconds >= 0",
            name=op.f("ck_meow_timing_sample_duration_nonnegative"),
        ),
        sa.CheckConstraint(
            "hazard_level IS NULL OR hazard_level BETWEEN 1 AND 6",
            name=op.f("ck_meow_timing_sample_hazard_level_range"),
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["azurpilot.app_instance.id"],
            name=op.f("fk_meow_timing_sample_instance_id_app_instance"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meow_timing_sample")),
        sa.UniqueConstraint(
            "idempotency_key", name=op.f("uq_meow_timing_sample_idempotency_key")
        ),
        schema="azurpilot",
    )
    op.create_index(
        "ix_meow_timing_instance_month_kind",
        "meow_timing_sample",
        ["instance_id", "month", "sample_kind"],
        unique=False,
        schema="azurpilot",
    )
    op.create_table(
        "monthly_aggregate",
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("metric", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Numeric(precision=30, scale=6), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("source_digest", sa.String(length=64), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "metric IN ('battle_count', 'akashi_encounters', 'meow_battle_raw_count', 'meow_battle_count')",
            name=op.f("ck_monthly_aggregate_metric_allowed"),
        ),
        sa.CheckConstraint(
            "EXTRACT(DAY FROM month) = 1",
            name=op.f("ck_monthly_aggregate_month_first_day"),
        ),
        sa.CheckConstraint(
            "source_digest IS NULL OR source_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_monthly_aggregate_source_digest_optional_sha256"),
        ),
        sa.CheckConstraint(
            "value >= 0", name=op.f("ck_monthly_aggregate_value_nonnegative")
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_monthly_aggregate_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["azurpilot.app_instance.id"],
            name=op.f("fk_monthly_aggregate_instance_id_app_instance"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "instance_id", "month", "metric", name=op.f("pk_monthly_aggregate")
        ),
        schema="azurpilot",
    )
    op.create_table(
        "opsi_item_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("payload_digest", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("imgid", sa.String(length=128), nullable=False),
        sa.Column("server", sa.String(length=32), nullable=True),
        sa.Column("zone", sa.String(length=128), nullable=True),
        sa.Column("zone_type", sa.String(length=64), nullable=True),
        sa.Column("zone_id", sa.Integer(), nullable=True),
        sa.Column("hazard_level", sa.Integer(), nullable=True),
        sa.Column("item_code", sa.String(length=128), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("tag", sa.String(length=64), nullable=True),
        sa.Column("genre", sa.String(length=64), nullable=False),
        sa.Column("combat_count", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "payload_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_opsi_item_event_payload_digest_sha256"),
        ),
        sa.CheckConstraint(
            "amount >= 0", name=op.f("ck_opsi_item_event_amount_nonnegative")
        ),
        sa.CheckConstraint(
            "combat_count IS NULL OR combat_count >= 0",
            name=op.f("ck_opsi_item_event_combat_count_nonnegative"),
        ),
        sa.CheckConstraint(
            "hazard_level IS NULL OR hazard_level BETWEEN 1 AND 6",
            name=op.f("ck_opsi_item_event_hazard_level_range"),
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["azurpilot.app_instance.id"],
            name=op.f("fk_opsi_item_event_instance_id_app_instance"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opsi_item_event")),
        sa.UniqueConstraint(
            "idempotency_key", name=op.f("uq_opsi_item_event_idempotency_key")
        ),
        schema="azurpilot",
    )
    op.create_index(
        "ix_opsi_item_imgid",
        "opsi_item_event",
        ["imgid"],
        unique=False,
        schema="azurpilot",
    )
    op.create_index(
        "ix_opsi_item_instance_genre_observed",
        "opsi_item_event",
        ["instance_id", "genre", "observed_at"],
        unique=False,
        schema="azurpilot",
    )
    op.create_table(
        "resource_current_state",
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("resource_code", sa.String(length=32), nullable=False),
        sa.Column("value", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "value >= 0", name=op.f("ck_resource_current_state_value_nonnegative")
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_resource_current_state_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["azurpilot.app_instance.id"],
            name=op.f("fk_resource_current_state_instance_id_app_instance"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "instance_id", "resource_code", name=op.f("pk_resource_current_state")
        ),
        schema="azurpilot",
    )
    op.create_table(
        "resource_snapshot",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("payload_digest", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("legacy_timestamp_text", sa.String(length=64), nullable=True),
        sa.Column("legacy_timezone", sa.String(length=64), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("oil", sa.BigInteger(), nullable=True),
        sa.Column("coin", sa.BigInteger(), nullable=True),
        sa.Column("gem", sa.BigInteger(), nullable=True),
        sa.Column("pt", sa.BigInteger(), nullable=True),
        sa.Column("cube", sa.BigInteger(), nullable=True),
        sa.Column("core", sa.BigInteger(), nullable=True),
        sa.Column("medal", sa.BigInteger(), nullable=True),
        sa.Column("merit", sa.BigInteger(), nullable=True),
        sa.Column("guild_coin", sa.BigInteger(), nullable=True),
        sa.Column("action_point", sa.BigInteger(), nullable=True),
        sa.Column("yellow_coin", sa.BigInteger(), nullable=True),
        sa.Column("purple_coin", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "payload_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_resource_snapshot_payload_digest_sha256"),
        ),
        sa.CheckConstraint(
            "action_point IS NULL OR action_point >= 0",
            name=op.f("ck_resource_snapshot_action_point_nonnegative"),
        ),
        sa.CheckConstraint(
            "coin IS NULL OR coin >= 0",
            name=op.f("ck_resource_snapshot_coin_nonnegative"),
        ),
        sa.CheckConstraint(
            "core IS NULL OR core >= 0",
            name=op.f("ck_resource_snapshot_core_nonnegative"),
        ),
        sa.CheckConstraint(
            "cube IS NULL OR cube >= 0",
            name=op.f("ck_resource_snapshot_cube_nonnegative"),
        ),
        sa.CheckConstraint(
            "gem IS NULL OR gem >= 0", name=op.f("ck_resource_snapshot_gem_nonnegative")
        ),
        sa.CheckConstraint(
            "guild_coin IS NULL OR guild_coin >= 0",
            name=op.f("ck_resource_snapshot_guild_coin_nonnegative"),
        ),
        sa.CheckConstraint(
            "medal IS NULL OR medal >= 0",
            name=op.f("ck_resource_snapshot_medal_nonnegative"),
        ),
        sa.CheckConstraint(
            "merit IS NULL OR merit >= 0",
            name=op.f("ck_resource_snapshot_merit_nonnegative"),
        ),
        sa.CheckConstraint(
            "oil IS NULL OR oil >= 0", name=op.f("ck_resource_snapshot_oil_nonnegative")
        ),
        sa.CheckConstraint(
            "pt IS NULL OR pt >= 0", name=op.f("ck_resource_snapshot_pt_nonnegative")
        ),
        sa.CheckConstraint(
            "purple_coin IS NULL OR purple_coin >= 0",
            name=op.f("ck_resource_snapshot_purple_coin_nonnegative"),
        ),
        sa.CheckConstraint(
            "yellow_coin IS NULL OR yellow_coin >= 0",
            name=op.f("ck_resource_snapshot_yellow_coin_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["azurpilot.app_instance.id"],
            name=op.f("fk_resource_snapshot_instance_id_app_instance"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resource_snapshot")),
        sa.UniqueConstraint(
            "idempotency_key", name=op.f("uq_resource_snapshot_idempotency_key")
        ),
        schema="azurpilot",
    )
    op.create_index(
        "ix_resource_snapshot_instance_observed_id",
        "resource_snapshot",
        [
            "instance_id",
            sa.literal_column("observed_at DESC NULLS LAST"),
            sa.literal_column("id DESC"),
        ],
        unique=False,
        schema="azurpilot",
    )
    op.create_table(
        "siren_research_device_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("payload_digest", sa.String(length=64), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("legacy_timestamp_text", sa.String(length=64), nullable=True),
        sa.Column("legacy_timezone", sa.String(length=64), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("hazard_level", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "(source = 'cl1' AND hazard_level IS NULL) OR (source = 'meow' AND hazard_level IS NOT NULL AND hazard_level BETWEEN 1 AND 6)",
            name=op.f("ck_siren_research_device_event_source_hazard_consistent"),
        ),
        sa.CheckConstraint(
            "payload_digest ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_siren_research_device_event_payload_digest_sha256"),
        ),
        sa.CheckConstraint(
            "source IN ('cl1', 'meow')",
            name=op.f("ck_siren_research_device_event_source_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["azurpilot.app_instance.id"],
            name=op.f("fk_siren_research_device_event_instance_id_app_instance"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_siren_research_device_event")),
        sa.UniqueConstraint(
            "idempotency_key",
            name=op.f("uq_siren_research_device_event_idempotency_key"),
        ),
        schema="azurpilot",
    )
    op.create_index(
        "ix_siren_device_event_instance_observed",
        "siren_research_device_event",
        ["instance_id", sa.literal_column("observed_at DESC NULLS LAST")],
        unique=False,
        schema="azurpilot",
    )
    op.create_table(
        "siren_research_device_stat",
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("hazard_level", sa.Integer(), server_default="0", nullable=False),
        sa.Column("device_count", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "(source = 'cl1' AND hazard_level = 0) OR (source = 'meow' AND hazard_level BETWEEN 1 AND 6)",
            name=op.f("ck_siren_research_device_stat_source_hazard_consistent"),
        ),
        sa.CheckConstraint(
            "EXTRACT(DAY FROM month) = 1",
            name=op.f("ck_siren_research_device_stat_month_first_day"),
        ),
        sa.CheckConstraint(
            "source IN ('cl1', 'meow')",
            name=op.f("ck_siren_research_device_stat_source_allowed"),
        ),
        sa.CheckConstraint(
            "device_count >= 0",
            name=op.f("ck_siren_research_device_stat_device_count_nonnegative"),
        ),
        sa.CheckConstraint(
            "hazard_level BETWEEN 0 AND 6",
            name=op.f("ck_siren_research_device_stat_hazard_level_range"),
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["azurpilot.app_instance.id"],
            name=op.f("fk_siren_research_device_stat_instance_id_app_instance"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "instance_id",
            "month",
            "source",
            "hazard_level",
            name=op.f("pk_siren_research_device_stat"),
        ),
        schema="azurpilot",
    )
    op.create_table(
        "commission_income_item",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("item_code", sa.String(length=128), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "amount >= 0", name=op.f("ck_commission_income_item_amount_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["azurpilot.commission_income_event.id"],
            name=op.f("fk_commission_income_item_event_id_commission_income_event"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "event_id", "item_code", name=op.f("pk_commission_income_item")
        ),
        schema="azurpilot",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откатить migration только на disposable Stage 2 DB."""
    if os.environ.get("AZURPILOT_POSTGRES_DISPOSABLE") != "1":
        raise RuntimeError("Откат разрешён только при AZURPILOT_POSTGRES_DISPOSABLE=1.")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("commission_income_item", schema="azurpilot")
    op.drop_table("siren_research_device_stat", schema="azurpilot")
    op.drop_index(
        "ix_siren_device_event_instance_observed",
        table_name="siren_research_device_event",
        schema="azurpilot",
    )
    op.drop_table("siren_research_device_event", schema="azurpilot")
    op.drop_index(
        "ix_resource_snapshot_instance_observed_id",
        table_name="resource_snapshot",
        schema="azurpilot",
    )
    op.drop_table("resource_snapshot", schema="azurpilot")
    op.drop_table("resource_current_state", schema="azurpilot")
    op.drop_index(
        "ix_opsi_item_instance_genre_observed",
        table_name="opsi_item_event",
        schema="azurpilot",
    )
    op.drop_index(
        "ix_opsi_item_imgid", table_name="opsi_item_event", schema="azurpilot"
    )
    op.drop_table("opsi_item_event", schema="azurpilot")
    op.drop_table("monthly_aggregate", schema="azurpilot")
    op.drop_index(
        "ix_meow_timing_instance_month_kind",
        table_name="meow_timing_sample",
        schema="azurpilot",
    )
    op.drop_table("meow_timing_sample", schema="azurpilot")
    op.drop_table("meow_hazard_aggregate", schema="azurpilot")
    op.drop_table("legacy_instance_alias", schema="azurpilot")
    op.drop_table("import_record", schema="azurpilot")
    op.drop_index(
        "ix_commission_income_instance_observed",
        table_name="commission_income_event",
        schema="azurpilot",
    )
    op.drop_table("commission_income_event", schema="azurpilot")
    op.drop_index(
        "ix_cl1_currency_instance_code_observed",
        table_name="cl1_currency_snapshot",
        schema="azurpilot",
    )
    op.drop_table("cl1_currency_snapshot", schema="azurpilot")
    op.drop_index(
        "ix_cl1_ap_snapshot_instance_observed",
        table_name="cl1_ap_snapshot",
        schema="azurpilot",
    )
    op.drop_table("cl1_ap_snapshot", schema="azurpilot")
    op.drop_index(
        "ix_cl1_ap_purchase_instance_observed",
        table_name="cl1_ap_purchase_event",
        schema="azurpilot",
    )
    op.drop_table("cl1_ap_purchase_event", schema="azurpilot")
    op.drop_table("ap_notification_state", schema="azurpilot")
    op.drop_table("import_batch", schema="azurpilot")
    op.drop_table("app_instance", schema="azurpilot")
    op.execute(DropSchema("azurpilot"))
    # ### end Alembic commands ###
