from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

DAILY_ORDER_CHALLENGE_EASY_SPECIAL_CHECK = Button(area=(829, 31, 853, 58), color=(174, 133, 123), button=(800, 81, 830, 108), file='./assets/en/island_daily_order/DAILY_ORDER_CHALLENGE_EASY_SPECIAL_CHECK.png')
DAILY_ORDER_CHECK = Button(area=(127, 21, 219, 45), color=(74, 83, 96), button=(127, 21, 219, 45), file='./assets/en/island_daily_order/DAILY_ORDER_CHECK.png')
DAILY_ORDER_DELIVER = Button(area=(1115, 640, 1170, 666), color=(96, 204, 255), button=(1115, 640, 1170, 666), file='./assets/en/island_daily_order/DAILY_ORDER_DELIVER.png')
DAILY_ORDER_LEVEL_UP = Button(area=(607, 280, 686, 356), color=(244, 113, 66), button=(607, 280, 686, 356), file='./assets/en/island_daily_order/DAILY_ORDER_LEVEL_UP.png')
DAILY_ORDER_PREPARING = Button(area=(948, 364, 1145, 416), color=(205, 205, 206), button=(948, 364, 1145, 416), file='./assets/en/island_daily_order/DAILY_ORDER_PREPARING.png')
DAILY_ORDER_REJECT = Button(area=(932, 640, 981, 666), color=(208, 208, 208), button=(932, 640, 981, 666), file='./assets/en/island_daily_order/DAILY_ORDER_REJECT.png')
DAILY_ORDER_RIGHT_PANEL_CHECK = Button(area=(858, 84, 988, 124), color=(197, 197, 196), button=(858, 84, 988, 124), file='./assets/en/island_daily_order/DAILY_ORDER_RIGHT_PANEL_CHECK.png')
DAILY_ORDER_URGENT_DELIVER = Button(area=(1021, 637, 1075, 667), color=(92, 202, 255), button=(1021, 637, 1075, 667), file='./assets/en/island_daily_order/DAILY_ORDER_URGENT_DELIVER.png')
DAILY_ORDER_URGENT_SPECIAL_CHECK = Button(area=(829, 31, 853, 58), color=(134, 127, 180), button=(800, 81, 830, 108), file='./assets/en/island_daily_order/DAILY_ORDER_URGENT_SPECIAL_CHECK.png')
ISLAND_PHONE_DAILY_ORDER = Button(area=(1000, 200, 1100, 250), color=(129, 189, 177), button=(1000, 200, 1100, 250), file='./assets/en/island_daily_order/ISLAND_PHONE_DAILY_ORDER.png')
POPUP_ORDER_CANNOT_REPLACE = Button(area=(508, 303, 707, 341), color=(85, 90, 96), button=(508, 303, 707, 341), file='./assets/en/island_daily_order/POPUP_ORDER_CANNOT_REPLACE.png')
POPUP_RESOURCE_INSUFFICIENT = Button(area=(508, 303, 707, 341), color=(85, 90, 96), button=(508, 303, 707, 341), file='./assets/en/island_daily_order/POPUP_RESOURCE_INSUFFICIENT.png')
TEMPLATE_CHEESE = Template(file='./assets/en/island_daily_order/TEMPLATE_CHEESE.png')
TEMPLATE_DAILY_ORDER_CHALLENGE = Template(file='./assets/en/island_daily_order/TEMPLATE_DAILY_ORDER_CHALLENGE.png')
TEMPLATE_DAILY_ORDER_EASY = Template(file='./assets/en/island_daily_order/TEMPLATE_DAILY_ORDER_EASY.png')
TEMPLATE_DAILY_ORDER_URGENT = Template(file='./assets/en/island_daily_order/TEMPLATE_DAILY_ORDER_URGENT.png')
TEMPLATE_DAILY_ORDER_URGENT_2 = Template(file='./assets/en/island_daily_order/TEMPLATE_DAILY_ORDER_URGENT_2.png')
TEMPLATE_TOFU = Template(file='./assets/en/island_daily_order/TEMPLATE_TOFU.png')
