Deploy:
  Python:
    PythonExecutable: ./.venv/bin/python
    PypiMirror: https://mirrors.aliyun.com/pypi/simple
    InstallDependencies: true

  Adb:
    AdbExecutable: ./.venv/bin/adb
    ReplaceAdb: false
    AutoConnect: true
    InstallUiautomator2: true

  Ocr:
    UseOcrServer: false
    StartOcrServer: false
    OcrServerPort: 22268
    OcrClientAddress: 127.0.0.1:22268

  Misc:
    DiscordRichPresence: false

  RemoteAccess:
    EnableRemoteAccess: true
    RemoteAccessMode: auto
    SSHUser: null
    SSHServer: remote.nanoda.work:1022
    SSHExecutable: /usr/bin/ssh
    AllowedRedirectHosts: null
    MaxRedirects: 2
    SignalingServer: null
    StunServers: ["stun:stun.l.google.com:19302"]
    TurnServers: null
    TurnCredentialMode: static

  Webui:
    WebuiHost: 0.0.0.0
    WebuiPort: 25548
    Language: zh-CN
    Theme: default
    DpiScaling: true
    EnableReload: true
    Password: null
    CDN: false
    Run: null
    WebuiSSLKey: null
    WebuiSSLCert: null
