from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BATTLE_PREPARATION = Button(area=(1031, 624, 1228, 682), color=(216, 160, 91), button=(1031, 624, 1228, 682), file='./assets/en/os_combat/BATTLE_PREPARATION.png')
SIREN_PREPARATION = Button(area=(1043, 639, 1240, 698), color=(131, 85, 102), button=(1043, 639, 1240, 698), file='./assets/en/os_combat/SIREN_PREPARATION.png')
