from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

COIN = Button(area=(272, 53, 317, 73), color=(221, 170, 75), button=(272, 53, 317, 73), file='./assets/en/reward/COIN.png')
EXP = Button(area=(455, 51, 490, 71), color=(133, 133, 145), button=(455, 51, 490, 71), file='./assets/en/reward/EXP.png')
MISSION_EMPTY = Button(area=(158, 348, 252, 373), color=(167, 171, 182), button=(158, 348, 252, 373), file='./assets/en/reward/MISSION_EMPTY.png')
MISSION_MULTI = Button(area=(1041, 8, 1101, 39), color=(221, 179, 96), button=(1041, 8, 1101, 39), file='./assets/en/reward/MISSION_MULTI.png')
MISSION_NOTICE = Button(area=(940, 670, 945, 681), color=(183, 83, 66), button=(940, 670, 945, 681), file='./assets/en/reward/MISSION_NOTICE.png')
MISSION_SINGLE = Button(area=(1130, 128, 1184, 150), color=(170, 204, 239), button=(1130, 128, 1184, 150), file='./assets/en/reward/MISSION_SINGLE.png')
MISSION_UNFINISH = Button(area=(1105, 124, 1165, 152), color=(168, 177, 199), button=(1105, 124, 1165, 152), file='./assets/en/reward/MISSION_UNFINISH.png')
MISSION_WEEKLY_RED_DOT = Button(area=(25, 500, 103, 531), color=(74, 58, 62), button=(25, 500, 103, 531), file='./assets/en/reward/MISSION_WEEKLY_RED_DOT.png')
OIL = Button(area=(114, 59, 149, 79), color=(70, 72, 72), button=(114, 59, 149, 79), file='./assets/en/reward/OIL.png')
