"""Безопасный прикладной слой локальной dev-сессии AzurPilot."""

from module.dev_runtime.contracts import (
    DEV_HOST,
    DEV_PORT,
    DEV_PROFILE,
    DevEnvironment,
    DevResult,
    DevSession,
    DevSessionState,
    DevTaskMode,
    DevTaskPhase,
    DevStatusKind,
    ProcessIdentity,
)
from module.dev_runtime.process import ProcessBackend
from module.dev_runtime.manager import DevSessionManager
from module.dev_runtime.evidence import (
    EVIDENCE_HEALTH_COMPLETE,
    EVIDENCE_HEALTH_CORRUPT,
    EVIDENCE_HEALTH_DEGRADED,
    EVIDENCE_HEALTH_UNAVAILABLE,
    EvidenceCorrupt,
    EvidenceError,
    EvidenceScreenshot,
    EvidenceStore,
    EvidenceUnavailable,
    GitSnapshot,
    TimelineEvent,
)
from module.dev_runtime.task_sandbox import (
    SCHEDULER_RESET_TIME,
    TASK_POLICY_FILE_ENV,
    TASK_POLICY_ROOT_ENV,
    TASK_POLICY_SESSION_ENV,
    TaskAuthorization,
    TaskCatalog,
    TaskDescriptor,
    TaskPlan,
    TaskPolicy,
    TaskPolicyContext,
    TaskPolicyStore,
    TaskProvenance,
    TaskRollbackResult,
    TaskSandboxError,
    rollback_task_dependency,
)

__all__ = [
    "DEV_HOST",
    "DEV_PORT",
    "DEV_PROFILE",
    "DevEnvironment",
    "DevResult",
    "DevSession",
    "DevSessionManager",
    "DevSessionState",
    "DevTaskMode",
    "DevTaskPhase",
    "DevStatusKind",
    "ProcessBackend",
    "ProcessIdentity",
    "EVIDENCE_HEALTH_COMPLETE",
    "EVIDENCE_HEALTH_CORRUPT",
    "EVIDENCE_HEALTH_DEGRADED",
    "EVIDENCE_HEALTH_UNAVAILABLE",
    "EvidenceCorrupt",
    "EvidenceError",
    "EvidenceScreenshot",
    "EvidenceStore",
    "EvidenceUnavailable",
    "GitSnapshot",
    "TimelineEvent",
    "SCHEDULER_RESET_TIME",
    "TASK_POLICY_FILE_ENV",
    "TASK_POLICY_ROOT_ENV",
    "TASK_POLICY_SESSION_ENV",
    "TaskAuthorization",
    "TaskCatalog",
    "TaskDescriptor",
    "TaskPlan",
    "TaskPolicy",
    "TaskPolicyContext",
    "TaskPolicyStore",
    "TaskProvenance",
    "TaskRollbackResult",
    "TaskSandboxError",
    "rollback_task_dependency",
]
