from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

COMMISSION_ADVICE = Button(area=(871, 328, 998, 362), color=(225, 181, 121), button=(871, 328, 998, 362), file='./assets/en/commission/COMMISSION_ADVICE.png')
COMMISSION_DAILY = Button(area=(30, 126, 75, 188), color=(170, 132, 92), button=(30, 126, 75, 188), file='./assets/en/commission/COMMISSION_DAILY.png')
COMMISSION_HAS_PENDING = Button(area=(320, 288, 380, 338), color=(121, 113, 152), button=(320, 288, 380, 338), file='./assets/en/commission/COMMISSION_HAS_PENDING.png')
COMMISSION_SCROLL_AREA = Button(area=(1254, 77, 1261, 676), color=(213, 183, 66), button=(1254, 77, 1261, 676), file='./assets/en/commission/COMMISSION_SCROLL_AREA.png')
COMMISSION_START = Button(area=(1053, 333, 1134, 361), color=(237, 199, 149), button=(1053, 333, 1134, 361), file='./assets/en/commission/COMMISSION_START.png')
COMMISSION_URGENT = Button(area=(28, 221, 76, 283), color=(169, 138, 95), button=(28, 221, 76, 283), file='./assets/en/commission/COMMISSION_URGENT.png')
EXP_INFO_S_REWARD = Button(area=(1138, 40, 1266, 145), color=(89, 115, 159), button=(1138, 40, 1266, 145), file='./assets/en/commission/EXP_INFO_S_REWARD.png')
FUEL_MAXED = Button(area=(388, 311, 478, 336), color=(87, 85, 94), button=(388, 311, 478, 336), file='./assets/en/commission/FUEL_MAXED.png')
OCR_FUEL_MAXED = Button(area=(428, 308, 482, 337), color=(99, 96, 101), button=(428, 308, 482, 337), file='./assets/en/commission/OCR_FUEL_MAXED.png')
OIL_MAXED = Button(area=(428, 310, 534, 335), color=(106, 103, 110), button=(428, 310, 534, 335), file='./assets/en/commission/OIL_MAXED.png')
REWARD_1 = Button(area=(403, 274, 504, 290), color=(241, 198, 145), button=(392, 262, 515, 303), file='./assets/en/commission/REWARD_1.png')
REWARD_SAVE_CLICK = Button(area=(415, 184, 496, 214), color=(152, 150, 168), button=(415, 184, 496, 214), file='./assets/en/commission/REWARD_SAVE_CLICK.png')
