import os

import imageio
import numpy as np
from tqdm.contrib.concurrent import process_map

from module.base.utils import get_bbox, get_color, image_size, load_image
from module.config.config_manual import ManualConfig as AzurLaneConfig
from module.logger import logger

MODULE_FOLDER = './module'
BUTTON_FILE = 'assets.py'
CANONICAL_SERVER = 'en'
IMPORT_EXP = """
from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.
"""
IMPORT_EXP = IMPORT_EXP.strip().split('\n') + ['']


class ImageExtractor:
    def __init__(self, module, file):
        self.module = module
        self.name, self.ext = os.path.splitext(file)
        self.area = None
        self.color = None
        self.button = None
        self.file = None
        self.load()

    def get_file(self, genre=''):
        for ext in ['.png', '.gif']:
            file = f'{self.name}.{genre}{ext}' if genre else f'{self.name}{ext}'
            path = os.path.join(
                AzurLaneConfig.ASSETS_FOLDER,
                CANONICAL_SERVER,
                self.module,
                file,
            ).replace('\\', '/')
            if os.path.exists(path):
                return path

        ext = '.png'
        file = f'{self.name}.{genre}{ext}' if genre else f'{self.name}{ext}'
        return os.path.join(
            AzurLaneConfig.ASSETS_FOLDER,
            CANONICAL_SERVER,
            self.module,
            file,
        ).replace('\\', '/')

    def extract(self, file):
        if os.path.splitext(file)[1] == '.gif':
            bbox = None
            mean = None
            for image in imageio.mimread(file):
                image = image[:, :, :3] if len(image.shape) == 3 else image
                new_bbox, new_mean = self._extract(image, file)
                if bbox is None:
                    bbox = new_bbox
                elif bbox != new_bbox:
                    logger.warning(
                        f'{file} has multiple different bbox, this will cause unexpected behaviour'
                    )
                if mean is None:
                    mean = new_mean
            return bbox, mean

        image = load_image(file)
        return self._extract(image, file)

    @staticmethod
    def _extract(image, file):
        size = image_size(image)
        if size != (1280, 720):
            logger.warning(f'{file} has wrong resolution: {size}')
        bbox = get_bbox(image)
        mean = get_color(image=image, area=bbox)
        mean = tuple(int(x) for x in np.rint(mean))
        return bbox, mean

    def load(self):
        file = self.get_file()
        if not os.path.exists(file):
            raise FileNotFoundError(
                f'Global asset is missing: {file}. Foreign-server fallback is disabled.'
            )

        area, color = self.extract(file)
        button = area
        override = self.get_file('AREA')
        if os.path.exists(override):
            area, _ = self.extract(override)
        override = self.get_file('COLOR')
        if os.path.exists(override):
            _, color = self.extract(override)
        override = self.get_file('BUTTON')
        if os.path.exists(override):
            button, _ = self.extract(override)

        self.area = area
        self.color = color
        self.button = button
        self.file = file

    @property
    def expression(self):
        return (
            f'{self.name} = Button('
            f'area={self.area!r}, color={self.color!r}, '
            f'button={self.button!r}, file={self.file!r})'
        )


class TemplateExtractor(ImageExtractor):
    @staticmethod
    def extract(file):
        image = load_image(file)
        bbox = get_bbox(image)
        mean = get_color(image=image, area=bbox)
        mean = tuple(int(x) for x in np.rint(mean))
        return bbox, mean

    @property
    def expression(self):
        return f'{self.name} = Template(file={self.file!r})'


class ModuleExtractor:
    def __init__(self, name):
        self.name = name
        self.folder = os.path.join(
            AzurLaneConfig.ASSETS_FOLDER,
            CANONICAL_SERVER,
            name,
        )

    @staticmethod
    def split(file):
        name, ext = os.path.splitext(file)
        name, sub = os.path.splitext(name)
        return name, sub, ext

    def is_base_image(self, file):
        _, sub, _ = self.split(file)
        return sub == ''

    @property
    def expression(self):
        exp = []
        for file in os.listdir(self.folder):
            if file[0].isdigit():
                continue
            if file.startswith('TEMPLATE_'):
                exp.append(TemplateExtractor(module=self.name, file=file).expression)
                continue
            if self.is_base_image(file):
                exp.append(ImageExtractor(module=self.name, file=file).expression)

        exp.sort()
        logger.info('Module: %s(%s)' % (self.name, len(exp)))
        return IMPORT_EXP + exp

    def write(self):
        folder = os.path.join(MODULE_FOLDER, self.name)
        if not os.path.exists(folder):
            os.mkdir(folder)
        with open(os.path.join(folder, BUTTON_FILE), 'w', newline='') as file:
            for text in self.expression:
                file.write(text + '\n')


def worker(module):
    ModuleExtractor(name=module).write()


class AssetExtractor:
    """Generate asset modules from the single canonical Global/EN root."""

    def __init__(self):
        logger.info('Assets extract: canonical root assets/en')
        root = os.path.join(AzurLaneConfig.ASSETS_FOLDER, CANONICAL_SERVER)
        modules = [
            module
            for module in os.listdir(root)
            if os.path.isdir(os.path.join(root, module))
        ]
        process_map(worker, modules)


if __name__ == '__main__':
    AssetExtractor()
