from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BUSINESS_DELIVERY_AMOMA_INTERACT = Button(area=(801, 479, 1033, 510), color=(231, 231, 231), button=(801, 479, 1033, 510), file='./assets/en/island_daily_interact/BUSINESS_DELIVERY_AMOMA_INTERACT.png')
BUSINESS_DELIVERY_THREE_OPTION_INTERACT = Button(area=(801, 412, 1033, 445), color=(228, 231, 228), button=(801, 412, 1033, 445), file='./assets/en/island_daily_interact/BUSINESS_DELIVERY_THREE_OPTION_INTERACT.png')
BUSINESS_DELIVERY_TWO_OPTION_INTERACT = Button(area=(801, 445, 1033, 476), color=(227, 229, 227), button=(801, 445, 1033, 476), file='./assets/en/island_daily_interact/BUSINESS_DELIVERY_TWO_OPTION_INTERACT.png')
DEVELOPMENT_PLAN_DAILY_TAB = Button(area=(25, 315, 96, 334), color=(101, 102, 104), button=(25, 315, 96, 334), file='./assets/en/island_daily_interact/DEVELOPMENT_PLAN_DAILY_TAB.png')
DEVELOPMENT_PLAN_DAILY_TAB_CHECK = Button(area=(25, 315, 96, 334), color=(127, 214, 255), button=(25, 315, 96, 334), file='./assets/en/island_daily_interact/DEVELOPMENT_PLAN_DAILY_TAB_CHECK.png')
DEVELOPMENT_PLAN_WEEKLY_TAB = Button(area=(25, 380, 96, 400), color=(95, 96, 99), button=(25, 380, 96, 400), file='./assets/en/island_daily_interact/DEVELOPMENT_PLAN_WEEKLY_TAB.png')
DEVELOPMENT_PLAN_WEEKLY_TAB_CHECK = Button(area=(25, 380, 96, 400), color=(123, 213, 255), button=(25, 380, 96, 400), file='./assets/en/island_daily_interact/DEVELOPMENT_PLAN_WEEKLY_TAB_CHECK.png')
ISLAND_DEVELOPMENT_PLAN_CHECK = Button(area=(124, 20, 289, 46), color=(96, 101, 114), button=(124, 20, 289, 46), file='./assets/en/island_daily_interact/ISLAND_DEVELOPMENT_PLAN_CHECK.png')
ISLAND_PHONE_DEVELOPMENT_PLAN = Button(area=(1059, 335, 1175, 373), color=(103, 219, 253), button=(1059, 335, 1175, 373), file='./assets/en/island_daily_interact/ISLAND_PHONE_DEVELOPMENT_PLAN.png')
JUU_EXPRESS_AMOMA_INTERACT = Button(area=(801, 479, 1033, 510), color=(224, 223, 223), button=(801, 479, 1033, 510), file='./assets/en/island_daily_interact/JUU_EXPRESS_AMOMA_INTERACT.png')
JUU_EXPRESS_AOBULAIEN_INTERACT = Button(area=(801, 445, 1033, 476), color=(227, 227, 224), button=(801, 445, 1033, 476), file='./assets/en/island_daily_interact/JUU_EXPRESS_AOBULAIEN_INTERACT.png')
JUU_EXPRESS_LISHA_INTERACT = Button(area=(801, 445, 1033, 476), color=(227, 228, 224), button=(801, 445, 1033, 476), file='./assets/en/island_daily_interact/JUU_EXPRESS_LISHA_INTERACT.png')
JUU_EXPRESS_LUXI_INTERACT = Button(area=(801, 412, 1033, 445), color=(225, 226, 226), button=(801, 412, 1033, 445), file='./assets/en/island_daily_interact/JUU_EXPRESS_LUXI_INTERACT.png')
JUU_EXPRESS_MEILI_INTERACT = Button(area=(801, 445, 1033, 476), color=(230, 230, 227), button=(801, 445, 1033, 476), file='./assets/en/island_daily_interact/JUU_EXPRESS_MEILI_INTERACT.png')
JUU_EXPRESS_PATELI_INTERACT = Button(area=(801, 445, 1033, 476), color=(231, 230, 231), button=(801, 445, 1033, 476), file='./assets/en/island_daily_interact/JUU_EXPRESS_PATELI_INTERACT.png')
JUU_EXPRESS_QIAOAN_INTERACT = Button(area=(801, 443, 1033, 480), color=(223, 225, 223), button=(801, 443, 1033, 480), file='./assets/en/island_daily_interact/JUU_EXPRESS_QIAOAN_INTERACT.png')
PET_CAT_FARM_INTERACT = Button(area=(801, 379, 1033, 408), color=(233, 234, 233), button=(801, 379, 1033, 408), file='./assets/en/island_daily_interact/PET_CAT_FARM_INTERACT.png')
ROUTE_THREE_OPTION_COMPLETE = Button(area=(801, 312, 1033, 344), color=(233, 235, 233), button=(801, 312, 1033, 344), file='./assets/en/island_daily_interact/ROUTE_THREE_OPTION_COMPLETE.png')
ROUTE_TWO_OPTION_COMPLETE = Button(area=(801, 344, 1033, 373), color=(231, 234, 231), button=(801, 344, 1033, 373), file='./assets/en/island_daily_interact/ROUTE_TWO_OPTION_COMPLETE.png')
TEMPLATE_BUSINESS_DELIVERY_TASK_ICON = Template(file='./assets/en/island_daily_interact/TEMPLATE_BUSINESS_DELIVERY_TASK_ICON.png')
TEMPLATE_JUU_EXPRESS_TASK_ICON = Template(file='./assets/en/island_daily_interact/TEMPLATE_JUU_EXPRESS_TASK_ICON.png')
TEMPLATE_WEEKLY_PHOTO_TASK_ICON = Template(file='./assets/en/island_daily_interact/TEMPLATE_WEEKLY_PHOTO_TASK_ICON.png')
WEEKLY_PHOTO_CAMERA = Button(area=(1110, 575, 1145, 610), color=(239, 240, 237), button=(1110, 575, 1145, 610), file='./assets/en/island_daily_interact/WEEKLY_PHOTO_CAMERA.png')
WEEKLY_PHOTO_IDLE = Button(area=(1080, 650, 1180, 720), color=(126, 181, 93), button=(1080, 650, 1180, 720), file='./assets/en/island_daily_interact/WEEKLY_PHOTO_IDLE.png')
WEEKLY_PHOTO_TASK_CHECK = Button(area=(647, 107, 804, 141), color=(127, 159, 148), button=(1207, 297, 1234, 321), file='./assets/en/island_daily_interact/WEEKLY_PHOTO_TASK_CHECK.png')
