from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

AWAKENING = Button(area=(802, 286, 896, 301), color=(200, 177, 127), button=(802, 286, 896, 301), file='./assets/en/awaken/AWAKENING.png')
AWAKEN_CANCEL = Button(area=(467, 517, 571, 541), color=(219, 168, 163), button=(467, 517, 571, 541), file='./assets/en/awaken/AWAKEN_CANCEL.png')
AWAKEN_CONFIRM = Button(area=(696, 516, 822, 541), color=(156, 185, 222), button=(696, 516, 822, 541), file='./assets/en/awaken/AWAKEN_CONFIRM.png')
AWAKEN_FINISH = Button(area=(435, 343, 468, 382), color=(58, 152, 193), button=(218, 561, 548, 630), file='./assets/en/awaken/AWAKEN_FINISH.png')
COST_ARRAY = Button(area=(720, 374, 780, 434), color=(141, 163, 178), button=(720, 374, 780, 434), file='./assets/en/awaken/COST_ARRAY.png')
COST_CHIP = Button(area=(610, 375, 670, 435), color=(157, 188, 190), button=(610, 375, 670, 435), file='./assets/en/awaken/COST_CHIP.png')
COST_COIN = Button(area=(499, 373, 559, 433), color=(219, 180, 83), button=(499, 373, 559, 433), file='./assets/en/awaken/COST_COIN.png')
LEVEL_UP = Button(area=(864, 286, 910, 302), color=(130, 158, 213), button=(864, 286, 910, 302), file='./assets/en/awaken/LEVEL_UP.png')
OCR_SHIP_EXP = Button(area=(1102, 276, 1250, 306), color=(255, 255, 255), button=(1102, 276, 1250, 306), file='./assets/en/awaken/OCR_SHIP_EXP.png')
OCR_SHIP_LEVEL = Button(area=(757, 283, 799, 319), color=(115, 130, 142), button=(757, 283, 799, 319), file='./assets/en/awaken/OCR_SHIP_LEVEL.png')
SHIP_LEVEL_CHECK = Button(area=(706, 298, 742, 315), color=(171, 162, 193), button=(706, 298, 742, 315), file='./assets/en/awaken/SHIP_LEVEL_CHECK.png')
