from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

MAIN_OCR_COIN = Button(area=(716, 24, 780, 49), color=(119, 126, 145), button=(716, 24, 780, 49), file='./assets/en/shipyard/MAIN_OCR_COIN.png')
SHIPYARD_CONFIRM_DEV = Button(area=(1067, 492, 1163, 518), color=(102, 140, 209), button=(1067, 492, 1163, 518), file='./assets/en/shipyard/SHIPYARD_CONFIRM_DEV.png')
SHIPYARD_CONFIRM_FATE = Button(area=(1145, 522, 1242, 555), color=(145, 173, 214), button=(1145, 522, 1242, 555), file='./assets/en/shipyard/SHIPYARD_CONFIRM_FATE.png')
SHIPYARD_GO_FATE = Button(area=(943, 508, 1018, 531), color=(181, 177, 58), button=(1080, 415, 1147, 505), file='./assets/en/shipyard/SHIPYARD_GO_FATE.png')
SHIPYARD_IN_DEV = Button(area=(956, 153, 1017, 165), color=(148, 156, 180), button=(956, 153, 1017, 165), file='./assets/en/shipyard/SHIPYARD_IN_DEV.png')
SHIPYARD_IN_FATE = Button(area=(924, 124, 1114, 144), color=(167, 161, 68), button=(924, 124, 1114, 144), file='./assets/en/shipyard/SHIPYARD_IN_FATE.png')
SHIPYARD_LEVEL_NOT_ENOUGH_DEV = Button(area=(1104, 149, 1273, 159), color=(162, 166, 181), button=(1104, 149, 1273, 159), file='./assets/en/shipyard/SHIPYARD_LEVEL_NOT_ENOUGH_DEV.png')
SHIPYARD_LEVEL_NOT_ENOUGH_FATE = Button(area=(1021, 160, 1151, 174), color=(88, 88, 90), button=(1021, 160, 1151, 174), file='./assets/en/shipyard/SHIPYARD_LEVEL_NOT_ENOUGH_FATE.png')
SHIPYARD_MINUS_DEV = Button(area=(1051, 431, 1081, 461), color=(76, 127, 195), button=(1051, 431, 1081, 461), file='./assets/en/shipyard/SHIPYARD_MINUS_DEV.png')
SHIPYARD_MINUS_FATE = Button(area=(1031, 450, 1067, 486), color=(76, 127, 195), button=(1031, 450, 1067, 486), file='./assets/en/shipyard/SHIPYARD_MINUS_FATE.png')
SHIPYARD_PLUS_DEV = Button(area=(1151, 431, 1181, 461), color=(83, 132, 199), button=(1151, 431, 1181, 461), file='./assets/en/shipyard/SHIPYARD_PLUS_DEV.png')
SHIPYARD_PLUS_FATE = Button(area=(1198, 449, 1234, 485), color=(86, 133, 200), button=(1198, 449, 1234, 485), file='./assets/en/shipyard/SHIPYARD_PLUS_FATE.png')
SHIPYARD_PROGRESS_DEV = Button(area=(1184, 145, 1273, 175), color=(80, 97, 142), button=(1184, 145, 1273, 175), file='./assets/en/shipyard/SHIPYARD_PROGRESS_DEV.png')
SHIPYARD_PROGRESS_FATE = Button(area=(1141, 153, 1278, 190), color=(82, 85, 89), button=(1141, 153, 1278, 190), file='./assets/en/shipyard/SHIPYARD_PROGRESS_FATE.png')
SHIPYARD_RESEARCH_COMPLETE = Button(area=(548, 498, 740, 531), color=(214, 142, 124), button=(548, 498, 740, 531), file='./assets/en/shipyard/SHIPYARD_RESEARCH_COMPLETE.png')
SHIPYARD_RESEARCH_INCOMPLETE = Button(area=(616, 490, 740, 531), color=(229, 192, 121), button=(616, 490, 740, 531), file='./assets/en/shipyard/SHIPYARD_RESEARCH_INCOMPLETE.png')
SHIPYARD_RESEARCH_IN_PROGRESS = Button(area=(465, 479, 482, 501), color=(105, 135, 173), button=(465, 479, 482, 501), file='./assets/en/shipyard/SHIPYARD_RESEARCH_IN_PROGRESS.png')
SHIPYARD_SERIES_SELECT_CHECK = Button(area=(32, 62, 53, 100), color=(9, 61, 190), button=(32, 62, 53, 100), file='./assets/en/shipyard/SHIPYARD_SERIES_SELECT_CHECK.png')
SHIPYARD_SERIES_SELECT_ENTER = Button(area=(34, 659, 160, 700), color=(66, 87, 138), button=(34, 659, 160, 700), file='./assets/en/shipyard/SHIPYARD_SERIES_SELECT_ENTER.png')
SHIPYARD_TOTAL_DEV = Button(area=(1091, 426, 1142, 466), color=(45, 48, 55), button=(1091, 426, 1142, 466), file='./assets/en/shipyard/SHIPYARD_TOTAL_DEV.png')
SHIPYARD_TOTAL_FATE = Button(area=(1100, 449, 1165, 486), color=(47, 51, 59), button=(1100, 449, 1165, 486), file='./assets/en/shipyard/SHIPYARD_TOTAL_FATE.png')
