from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

DAILY_ACTIVE = Button(area=(673, 357, 705, 396), color=(5, 9, 10), button=(673, 357, 705, 396), file='./assets/en/daily/DAILY_ACTIVE.png')
DAILY_ENTER = Button(area=(534, 118, 744, 645), color=(132, 161, 180), button=(534, 118, 744, 645), file='./assets/en/daily/DAILY_ENTER.png')
DAILY_ENTER_CHECK = Button(area=(1221, 136, 1230, 143), color=(247, 214, 82), button=(1221, 136, 1230, 143), file='./assets/en/daily/DAILY_ENTER_CHECK.png')
DAILY_FLEET_NEXT = Button(area=(914, 325, 931, 354), color=(86, 115, 149), button=(914, 325, 931, 354), file='./assets/en/daily/DAILY_FLEET_NEXT.png')
DAILY_FLEET_PREV = Button(area=(36, 325, 53, 354), color=(103, 130, 163), button=(36, 325, 53, 354), file='./assets/en/daily/DAILY_FLEET_PREV.png')
DAILY_LOCKED = Button(area=(710, 359, 748, 409), color=(24, 29, 29), button=(710, 359, 748, 409), file='./assets/en/daily/DAILY_LOCKED.png')
DAILY_MISSION_1 = Button(area=(584, 203, 701, 214), color=(62, 83, 124), button=(584, 203, 701, 214), file='./assets/en/daily/DAILY_MISSION_1.png')
DAILY_MISSION_2 = Button(area=(584, 363, 701, 374), color=(65, 88, 128), button=(584, 363, 701, 374), file='./assets/en/daily/DAILY_MISSION_2.png')
DAILY_MISSION_3 = Button(area=(583, 522, 701, 534), color=(73, 101, 139), button=(583, 522, 701, 534), file='./assets/en/daily/DAILY_MISSION_3.png')
DAILY_NEXT = Button(area=(811, 151, 1004, 612), color=(66, 44, 39), button=(811, 151, 1004, 612), file='./assets/en/daily/DAILY_NEXT.png')
DAILY_NORMAL_RUN = Button(area=(413, 299, 555, 345), color=(244, 179, 108), button=(413, 299, 555, 345), file='./assets/en/daily/DAILY_NORMAL_RUN.png')
DAILY_PREV = Button(area=(282, 163, 456, 600), color=(57, 70, 69), button=(282, 163, 456, 600), file='./assets/en/daily/DAILY_PREV.png')
DAILY_SKIP = Button(area=(1034, 331, 1116, 340), color=(182, 201, 227), button=(1034, 331, 1116, 340), file='./assets/en/daily/DAILY_SKIP.png')
ENTRANCE_EMERGENCY_MODULE_DEVELOPMENT = Button(area=(606, 246, 673, 293), color=(198, 178, 199), button=(606, 246, 673, 293), file='./assets/en/daily/ENTRANCE_EMERGENCY_MODULE_DEVELOPMENT.png')
OCR_DAILY_FLEET_INDEX = Button(area=(525, 605, 561, 667), color=(60, 90, 139), button=(525, 605, 561, 667), file='./assets/en/daily/OCR_DAILY_FLEET_INDEX.png')
OCR_REMAIN = Button(area=(526, 114, 546, 144), color=(94, 132, 164), button=(526, 114, 546, 144), file='./assets/en/daily/OCR_REMAIN.png')
