from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ESCORT_CHECK = Button(area=(128, 16, 346, 38), color=(109, 126, 164), button=(128, 16, 346, 38), file='./assets/en/event/ESCORT_CHECK.png')
ESCORT_HARD_ENTRANCE = Button(area=(128, 16, 346, 38), color=(109, 126, 164), button=(745, 284, 886, 392), file='./assets/en/event/ESCORT_HARD_ENTRANCE.png')
ESCORT_REMAIN = Button(area=(41, 673, 113, 691), color=(125, 142, 130), button=(41, 673, 113, 691), file='./assets/en/event/ESCORT_REMAIN.png')
MAIN_GOTO_ESCORT = Button(area=(609, 265, 654, 307), color=(216, 184, 171), button=(609, 265, 654, 307), file='./assets/en/event/MAIN_GOTO_ESCORT.png')
