from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

OS_SHOP_CHECK = Button(area=(346, 160, 361, 183), color=(22, 49, 117), button=(346, 160, 361, 183), file='./assets/en/os_shop/OS_SHOP_CHECK.png')
OS_SHOP_PURPLE_COINS = Button(area=(1043, 155, 1178, 189), color=(28, 45, 96), button=(1043, 155, 1178, 189), file='./assets/en/os_shop/OS_SHOP_PURPLE_COINS.png')
OS_SHOP_SAFE_AREA = Button(area=(1130, 196, 1172, 488), color=(20, 42, 102), button=(1130, 196, 1172, 488), file='./assets/en/os_shop/OS_SHOP_SAFE_AREA.png')
OS_SHOP_SCROLL_AREA = Button(area=(1176, 210, 1180, 720), color=(255, 255, 255), button=(1176, 210, 1180, 720), file='./assets/en/os_shop/OS_SHOP_SCROLL_AREA.png')
PORT_SUPPLY_CHECK = Button(area=(127, 15, 264, 39), color=(131, 145, 186), button=(127, 15, 264, 39), file='./assets/en/os_shop/PORT_SUPPLY_CHECK.png')
SHOP_BUY_CONFIRM = Button(area=(708, 484, 875, 538), color=(106, 151, 207), button=(708, 484, 875, 538), file='./assets/en/os_shop/SHOP_BUY_CONFIRM.png')
SHOP_PURPLE_COINS = Button(area=(379, 106, 489, 137), color=(102, 107, 118), button=(379, 106, 489, 137), file='./assets/en/os_shop/SHOP_PURPLE_COINS.png')
SHOP_YELLOW_COINS = Button(area=(1038, 27, 1128, 48), color=(71, 74, 76), button=(1038, 27, 1128, 48), file='./assets/en/os_shop/SHOP_YELLOW_COINS.png')
