from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

DOSSIER_REWARD_CHECK = Button(area=(120, 14, 316, 39), color=(130, 105, 104), button=(120, 14, 316, 39), file='./assets/en/meta_reward/DOSSIER_REWARD_CHECK.png')
DOSSIER_REWARD_ENTER = Button(area=(244, 645, 404, 709), color=(104, 87, 80), button=(244, 645, 404, 709), file='./assets/en/meta_reward/DOSSIER_REWARD_ENTER.png')
DOSSIER_REWARD_RECEIVE = Button(area=(426, 617, 432, 628), color=(214, 117, 103), button=(320, 622, 428, 651), file='./assets/en/meta_reward/DOSSIER_REWARD_RECEIVE.png')
META_REWARD_NOTICE = Button(area=(1070, 508, 1075, 523), color=(249, 182, 57), button=(1070, 508, 1075, 523), file='./assets/en/meta_reward/META_REWARD_NOTICE.png')
REWARD_CHECK = Button(area=(35, 487, 62, 541), color=(203, 169, 170), button=(35, 487, 62, 541), file='./assets/en/meta_reward/REWARD_CHECK.png')
REWARD_ENTER = Button(area=(1106, 532, 1199, 544), color=(213, 212, 217), button=(1106, 532, 1199, 544), file='./assets/en/meta_reward/REWARD_ENTER.png')
REWARD_RECEIVE = Button(area=(1067, 608, 1182, 633), color=(164, 92, 93), button=(1067, 608, 1182, 633), file='./assets/en/meta_reward/REWARD_RECEIVE.png')
SYNC_ENTER = Button(area=(860, 352, 945, 369), color=(144, 128, 131), button=(860, 352, 945, 369), file='./assets/en/meta_reward/SYNC_ENTER.png')
SYNC_ENTER2 = Button(area=(866, 351, 943, 370), color=(132, 117, 119), button=(866, 351, 943, 370), file='./assets/en/meta_reward/SYNC_ENTER2.png')
SYNC_REWARD_NOTICE = Button(area=(977, 337, 981, 352), color=(250, 182, 57), button=(977, 337, 981, 352), file='./assets/en/meta_reward/SYNC_REWARD_NOTICE.png')
SYNC_TAP = Button(area=(581, 339, 707, 377), color=(129, 80, 80), button=(581, 339, 707, 377), file='./assets/en/meta_reward/SYNC_TAP.png')
