from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ISLAND_FISHERY_POST1 = Button(area=(199, 260, 285, 288), color=(117, 188, 222), button=(258, 316, 333, 391), file='./assets/en/island_rancher/ISLAND_FISHERY_POST1.png')
ISLAND_FISHERY_POST2 = Button(area=(199, 260, 285, 288), color=(117, 188, 222), button=(353, 316, 428, 390), file='./assets/en/island_rancher/ISLAND_FISHERY_POST2.png')
ISLAND_FISHERY_POST3 = Button(area=(199, 260, 285, 288), color=(117, 188, 222), button=(451, 322, 518, 387), file='./assets/en/island_rancher/ISLAND_FISHERY_POST3.png')
ISLAND_RANCH_POST1 = Button(area=(738, 78, 824, 105), color=(117, 188, 222), button=(798, 137, 871, 209), file='./assets/en/island_rancher/ISLAND_RANCH_POST1.png')
ISLAND_RANCH_POST2 = Button(area=(738, 78, 824, 105), color=(117, 188, 222), button=(891, 132, 968, 210), file='./assets/en/island_rancher/ISLAND_RANCH_POST2.png')
ISLAND_RANCH_POST3 = Button(area=(738, 78, 824, 105), color=(117, 188, 222), button=(985, 132, 1063, 210), file='./assets/en/island_rancher/ISLAND_RANCH_POST3.png')
ISLAND_RANCH_POST4 = Button(area=(738, 78, 824, 105), color=(117, 188, 222), button=(1080, 132, 1158, 210), file='./assets/en/island_rancher/ISLAND_RANCH_POST4.png')
MILL_CATTLE_FEED = Button(area=(593, 233, 656, 298), color=(202, 196, 187), button=(593, 233, 656, 298), file='./assets/en/island_rancher/MILL_CATTLE_FEED.png')
MILL_CHICKEN_FEED = Button(area=(265, 235, 331, 296), color=(212, 199, 172), button=(265, 235, 331, 296), file='./assets/en/island_rancher/MILL_CHICKEN_FEED.png')
MILL_PIG_FEED = Button(area=(431, 228, 492, 298), color=(204, 192, 175), button=(431, 228, 492, 298), file='./assets/en/island_rancher/MILL_PIG_FEED.png')
MILL_SHEEP_FEED = Button(area=(756, 227, 819, 301), color=(198, 195, 175), button=(756, 227, 819, 301), file='./assets/en/island_rancher/MILL_SHEEP_FEED.png')
MILL_WHEAT_FLOUR = Button(area=(917, 233, 983, 299), color=(196, 183, 167), button=(917, 233, 983, 299), file='./assets/en/island_rancher/MILL_WHEAT_FLOUR.png')
SELECT_CRAY = Button(area=(213, 152, 284, 209), color=(156, 155, 163), button=(213, 152, 284, 209), file='./assets/en/island_rancher/SELECT_CRAY.png')
SELECT_CRAY_CHECK = Button(area=(741, 239, 844, 321), color=(158, 157, 165), button=(741, 239, 844, 321), file='./assets/en/island_rancher/SELECT_CRAY_CHECK.png')
TEMPLATE_CATTLE_FEED = Template(file='./assets/en/island_rancher/TEMPLATE_CATTLE_FEED.png')
TEMPLATE_CHICKEN = Template(file='./assets/en/island_rancher/TEMPLATE_CHICKEN.png')
TEMPLATE_CHICKEN_FEED = Template(file='./assets/en/island_rancher/TEMPLATE_CHICKEN_FEED.png')
TEMPLATE_CRAY = Template(file='./assets/en/island_rancher/TEMPLATE_CRAY.png')
TEMPLATE_PIG_FEED = Template(file='./assets/en/island_rancher/TEMPLATE_PIG_FEED.png')
TEMPLATE_PORK = Template(file='./assets/en/island_rancher/TEMPLATE_PORK.png')
TEMPLATE_SHEEP_FEED = Template(file='./assets/en/island_rancher/TEMPLATE_SHEEP_FEED.png')
