from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

CAMPAIGN_BONUS = Button(area=(406, 150, 477, 162), color=(199, 204, 212), button=(406, 150, 477, 162), file='./assets/en/statistics/CAMPAIGN_BONUS.png')
CAMPAIGN_BONUS_SINGLE = Button(area=(404, 149, 439, 166), color=(175, 193, 208), button=(404, 149, 439, 166), file='./assets/en/statistics/CAMPAIGN_BONUS_SINGLE.png')
ENEMY_NAME = Button(area=(781, 283, 965, 322), color=(92, 102, 119), button=(781, 283, 965, 322), file='./assets/en/statistics/ENEMY_NAME.png')
GET_ITEMS_ODD = Button(area=(628, 294, 653, 397), color=(98, 103, 121), button=(628, 294, 653, 397), file='./assets/en/statistics/GET_ITEMS_ODD.png')
